# Credit Risk Detection — Full MLOps Pipeline

**University MLOps Group 10**

This notebook runs the complete credit risk detection pipeline end-to-end


> **Note**: The data pipeline (PDF extraction, label building, embedding generation) has already been run and the outputs are committed to the repo under `data/processed/`, `data/embeddings/`, `data/labels/`, and `data/finetune/`. This notebook skips those steps and goes straight to inference.

---
## Section 1: Setup

Check the GPU, clone the repository, install all Python dependencies, and configure environment variables.

In [1]:
# Verify GPU availability — you should see a T4 (or better)
!nvidia-smi

Sun Apr 26 14:46:58 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [2]:
import os


GITHUB_REPO_URL = "https://github.com/pankti0/MLOps-group-10"
USE_MANUAL_UPLOAD = False  # Set True to skip cloning and upload manually

REPO_DIR = "/content/MLOps-group-10"

if USE_MANUAL_UPLOAD:
    print("Manual upload mode selected.")
    print("Please upload the repo zip via Files panel and unzip to /content/MLOps-group-10")
    print("  !unzip /content/MLOps-group-10.zip -d /content/")
elif not os.path.isdir(REPO_DIR):
    print(f"Cloning {GITHUB_REPO_URL} ...")
    !git clone {GITHUB_REPO_URL} {REPO_DIR}
    print("Clone complete.")
else:
    print(f"Repo already exists at {REPO_DIR}, pulling latest...")
    !git -C {REPO_DIR} pull

Cloning https://github.com/pankti0/MLOps-group-10 ...
Cloning into '/content/MLOps-group-10'...
remote: Enumerating objects: 8422, done.
remote: Counting objects: 100% (316/316), done.
remote: Compressing objects: 100% (183/183), done.
remote: Total 8422 (delta 165), reused 258 (delta 118), pack-reused 8106 (from 2)
Receiving objects: 100% (8422/8422), 151.79 MiB | 13.43 MiB/s, done.
Resolving deltas: 100% (1350/1350), done.
Updating files: 100% (7769/7769), done.
Clone complete.

In [3]:
# Install all project dependencies.
print("Installing dependencies from requirements.txt ...")
!pip install -q -r /content/MLOps-group-10/requirements.txt

# Ensure bitsandbytes is the CUDA-enabled version
!pip install -q bitsandbytes>=0.41.0

print("All dependencies installed.")

Installing dependencies from requirements.txt ...
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 kB 6.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.0/25.0 MB 61.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 131.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 87.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 697.4/697.4 kB 55.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 10.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 116.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.2/23.2 MB 93.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 112.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.0/527.0 kB 44.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 30.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 102.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 73.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.4/542.4 kB 46.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 103.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.2/180.2 kB 20.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.6/231.6 kB 24.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 20.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 122.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 5.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.33.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-exporter-otlp-proto-common==1.38.0, but you have opentelemetry-exporter-otlp-proto-common 1.41.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-proto==1.38.0, but you have opentelemetry-proto 1.41.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-sdk~=1.38.0, but you have opentelemetry-sdk 1.41.1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.41.1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.41.1 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.41.1 which is incompatible.
All dependencies installed.

In [4]:

# Configure environment variables.
#


try:
    from google.colab import userdata
    # Try loading from Colab Secrets
    HF_TOKEN = userdata.get('HF_TOKEN')
    WANDB_API_KEY = userdata.get('WANDB_API_KEY')
    print("Loaded secrets from Colab Secrets vault.")
except Exception:
    # Fallback: assign directly
    HF_TOKEN = "hf_YOUR_TOKEN_HERE"
    WANDB_API_KEY = "YOUR_WANDB_API_KEY_HERE"
    print("Using directly-assigned API keys (Colab Secrets not available).")

os.environ["HF_TOKEN"] = HF_TOKEN
os.environ["HUGGING_FACE_HUB_TOKEN"] = HF_TOKEN
os.environ["WANDB_API_KEY"] = WANDB_API_KEY


env_content = f"""HF_TOKEN={HF_TOKEN}
HUGGING_FACE_HUB_TOKEN={HF_TOKEN}
WANDB_API_KEY={WANDB_API_KEY}
"""
with open("/content/MLOps-group-10/.env", "w") as f:
    f.write(env_content)

print("Environment variables configured.")

Loaded secrets from Colab Secrets vault.
Environment variables configured.

In [5]:
%cd MLOps-group-10

/content/MLOps-group-10

---
## Section 2: Weights & Biases Login

All training runs, inference runs, and evaluation metrics are logged to W&B for experiment tracking.
If you haven't already, create a free account at [wandb.ai](https://wandb.ai).

In [6]:
import wandb

# Log in using the API key set in Section 1.
# If WANDB_API_KEY env var is set, this proceeds non-interactively.
wandb.login()
print(f"W&B version: {wandb.__version__}")
print("Logged in to Weights & Biases successfully.")

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from WANDB_API_KEY.
wandb: Currently logged in as: pankti0 (pankti0-singapore-university-of-technology-and-design) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

W&B version: 0.25.1
Logged in to Weights & Biases successfully.

---
## Section 3: Verify Pre-Processed Data

The following data artefacts were generated by the data pipeline and are committed to the repo.
This cell verifies they all exist before running inference:

- `data/processed/` — per-company JSON files with extracted 10-K sections
- `data/labels/company_labels.csv` — ground-truth credit risk labels
- `data/embeddings/faiss.index` + `chunk_metadata.json` — vector store for RAG
- `data/finetune/train.jsonl`, `val.jsonl`, `test.jsonl` — fine-tuning data

In [7]:
import os
import pandas as pd

REPO_ROOT = "."  # or the absolute path to your repo

required_paths = {
    "Labels CSV"     : f"{REPO_ROOT}/data/labels/company_labels.csv",
    "FAISS index"    : f"{REPO_ROOT}/data/embeddings/faiss.index",
    "Chunk metadata" : f"{REPO_ROOT}/data/embeddings/chunk_metadata.json",
}

# Check cross-validation folds
folds = [1, 2, 3, 4, 5]
for fold in folds:
    for split in ["train", "val", "test"]:
        path = f"{REPO_ROOT}/data/finetune/fold_{fold}/{split}.jsonl"
        required_paths[f"Fold {fold} {split.capitalize()} JSONL"] = path

all_ok = True
for name, path in required_paths.items():
    exists = os.path.isfile(path)
    status = "OK" if exists else "MISSING"
    print(f"  [{status}] {name}: {path}")
    if not exists:
        all_ok = False

processed_dir = f"{REPO_ROOT}/data/processed/"
processed_files = [f for f in os.listdir(processed_dir) if f.endswith(".json") and "sections" in f]
print(f"\n  [OK] Processed sections: {len(processed_files)} companies")
for f in sorted(processed_files):
    print(f"       {f}")

if all_ok:
    print("\nAll required data files present — ready to run inference.")
else:
    print("\nWARNING: Some files are missing. Re-run the data pipeline scripts if needed.")

  [OK] Labels CSV: ./data/labels/company_labels.csv
  [OK] FAISS index: ./data/embeddings/faiss.index
  [OK] Chunk metadata: ./data/embeddings/chunk_metadata.json
  [OK] Fold 1 Train JSONL: ./data/finetune/fold_1/train.jsonl
  [OK] Fold 1 Val JSONL: ./data/finetune/fold_1/val.jsonl
  [OK] Fold 1 Test JSONL: ./data/finetune/fold_1/test.jsonl
  [OK] Fold 2 Train JSONL: ./data/finetune/fold_2/train.jsonl
  [OK] Fold 2 Val JSONL: ./data/finetune/fold_2/val.jsonl
  [OK] Fold 2 Test JSONL: ./data/finetune/fold_2/test.jsonl
  [OK] Fold 3 Train JSONL: ./data/finetune/fold_3/train.jsonl
  [OK] Fold 3 Val JSONL: ./data/finetune/fold_3/val.jsonl
  [OK] Fold 3 Test JSONL: ./data/finetune/fold_3/test.jsonl
  [OK] Fold 4 Train JSONL: ./data/finetune/fold_4/train.jsonl
  [OK] Fold 4 Val JSONL: ./data/finetune/fold_4/val.jsonl
  [OK] Fold 4 Test JSONL: ./data/finetune/fold_4/test.jsonl
  [OK] Fold 5 Train JSONL: ./data/finetune/fold_5/train.jsonl
  [OK] Fold 5 Val JSONL: ./data/finetune/fold_5/val.jsonl
  [OK] Fold 5 Test JSONL: ./data/finetune/fold_5/test.jsonl

  [OK] Processed sections: 30 companies
       AAL_sections.json
       AAPL_sections.json
       AMC_sections.json
       AMZN_sections.json
       ARE_sections.json
       AVGO_sections.json
       CAT_sections.json
       CHTR_sections.json
       CI_sections.json
       CMCSA_sections.json
       CNC_sections.json
       DAL_sections.json
       ELV_sections.json
       FLUT_sections.json
       FNMA_sections.json
       F_sections.json
       GME_sections.json
       GOOGL_sections.json
       HD_sections.json
       JNJ_sections.json
       KHC_sections.json
       KMX_sections.json
       MU_sections.json
       PARA_sections.json
       TMUS_sections.json
       TXN_sections.json
       T_sections.json
       UNH_sections.json
       VLO_sections.json
       VZ_sections.json

All required data files present — ready to run inference.

In [7]:
# Display company labels — these are the ground-truth credit risk labels
import pandas as pd
from IPython.display import display

labels_df = pd.read_csv("/content/MLOps-group-10/data/labels/company_labels.csv")

def style_risk(val):
    colors = {"low": "#d4edda", "medium": "#fff3cd", "high": "#f8d7da"}
    return f"background-color: {colors.get(str(val).lower(), '')}"

print(f"Dataset: {len(labels_df)} companies")
display(
    labels_df.style
    .applymap(style_risk, subset=["risk_category"])
    .format({"risk_score": "{:.0f}"})
    .set_caption("Company Credit Risk Labels (Ground Truth)")
)

Dataset: 32 companies

/tmp/ipykernel_640/669797996.py:14: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  .applymap(style_risk, subset=["risk_category"])

In [10]:
# Show FAISS index statistics
import json
import faiss

index = faiss.read_index("/content/MLOps-group-10/data/embeddings/faiss.index")
with open("/content/MLOps-group-10/data/embeddings/chunk_metadata.json") as f:
    metadata = json.load(f)

print("FAISS Index Statistics")
print(f"  Total vectors : {index.ntotal}")
print(f"  Dimension     : {index.d}")
print(f"  Metadata chunks: {len(metadata)}")

# Show a sample chunk
if metadata:
    sample = metadata[0]
    print(f"\nSample chunk keys: {list(sample.keys())}")
    print(f"  ticker : {sample.get('ticker', 'N/A')}")
    print(f"  section: {sample.get('section', 'N/A')}")
    print(f"  text   : {str(sample.get('text', ''))[:120]}...")

FAISS Index Statistics
  Total vectors : 1272
  Dimension     : 768
  Metadata chunks: 1272

Sample chunk keys: ['text', 'chunk_id', 'metadata', 'char_start', 'char_end']
  ticker : N/A
  section: N/A
  text   :

Item 1A.
Risk Factors
The following summarizes factors that could have a material adverse effect on the Company’s bus...

---
## Section 4: Baseline Inference

Run credit risk inference using **direct prompting** (no retrieval, no fine-tuning).

- Model: `mistralai/Mistral-7B-Instruct-v0.2`
- Quantization: 4-bit NF4 via `bitsandbytes`
- The model reads raw 10-K section text and outputs a risk score + label

## ⚡️ Standardized Stratified K-Fold Cross-Validation (NEW)

All experiments now use **stratified k-fold cross-validation** for robust, fair, and reproducible evaluation.

- Use the `--fold` and `--split` arguments in all inference commands.

- Results are saved as `results/{approach}_fold{N}_{split}.csv`.

- Update all result display code to use the correct fold/split files.

You can loop over all folds for full evaluation.

In [12]:
!git pull

remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0 (from 0)
Unpacking objects: 100% (4/4), 761 bytes | 761.00 KiB/s, done.
From https://github.com/pankti0/MLOps-group-10
   83229c0..8132893  main       -> origin/main
Updating 83229c0..8132893
Fast-forward
 scripts/train_lora.py | 32 ++++++++++++++++++++++++++------
 1 file changed, 26 insertions(+), 6 deletions(-)

In [11]:
# Run baseline inference for all folds (1-5) on the test split
for fold in range(1, 6):
    print(f"Running baseline inference for fold {fold} (test split)...")
    !python3 scripts/run_inference_all.py --approach baseline --fold {fold} --split test

Running baseline inference for fold 1 (test split)...
03:07:32 [INFO] run_inference_all: Starting inference: approach=baseline, mock=False.
03:07:32 [INFO] numexpr.utils: NumExpr defaulting to 2 threads.
03:07:33 [INFO] run_inference_all: Loaded 7 companies for fold 1 split 'test'.
03:07:35 [INFO] run_inference_all: Loading model 'mistralai/Mistral-7B-Instruct-v0.2' (quantize=True).
03:07:41 [INFO] src.models.base_loader: HF_TOKEN found — using authenticated HuggingFace download.
03:07:41 [INFO] src.models.base_loader: Loading tokenizer for 'mistralai/Mistral-7B-Instruct-v0.2'.
03:07:41 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
03:07:41 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
03:07:41 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
03:07:41 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
03:07:41 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
03:07:41 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
03:07:42 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
03:07:42 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
03:07:42 [INFO] src.models.base_loader: 4-bit NF4 quantisation enabled.
03:07:42 [INFO] src.models.base_loader: Loading model 'mistralai/Mistral-7B-Instruct-v0.2' (device_map='auto').
03:07:42 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
03:07:42 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
03:07:43 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
03:07:43 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 291/291 [00:59<00:00,  4.90it/s, Materializing param=model.norm.weight]
03:08:46 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
03:08:46 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
03:08:46 [INFO] src.models.base_loader: Model loaded and set to eval mode.
[baseline] Analyzing companies:   0% 0/7 [00:00<?, ?company/s]03:08:46 [INFO] src.models.baseline_agent: [baseline] Analyzing Johnson & Johnson (JNJ).
03:09:17 [INFO] src.models.baseline_agent: [baseline] JNJ -> score=20.0, label=0, level=low
[baseline] Analyzing companies:  14% 1/7 [00:30<03:01, 30.17s/company]03:09:17 [INFO] src.models.baseline_agent: [baseline] Analyzing Delta Air Lines (DAL).
03:09:41 [INFO] src.models.baseline_agent: [baseline] DAL -> score=30.0, label=0, level=low
[baseline] Analyzing companies:  29% 2/7 [00:54<02:12, 26.57s/company]03:09:41 [INFO] src.models.baseline_agent: [baseline] Analyzing Ford Motor Company (F).
03:10:22 [INFO] src.models.baseline_agent: [baseline] F -> score=35.0, label=0, level=low
[baseline] Analyzing companies:  43% 3/7 [01:35<02:13, 33.31s/company]03:10:22 [INFO] src.models.baseline_agent: [baseline] Analyzing Amazon (AMZN).
03:11:00 [INFO] src.models.baseline_agent: [baseline] AMZN -> score=30.0, label=0, level=low
[baseline] Analyzing companies:  57% 4/7 [02:13<01:45, 35.13s/company]03:11:00 [INFO] src.models.baseline_agent: [baseline] Analyzing Carmax (KMX).
03:11:25 [INFO] src.models.baseline_agent: [baseline] KMX -> score=30.0, label=0, level=low
[baseline] Analyzing companies:  71% 5/7 [02:38<01:02, 31.41s/company]03:11:25 [INFO] src.models.baseline_agent: [baseline] Analyzing Charter Communications (CHTR).
03:11:55 [INFO] src.models.baseline_agent: [baseline] CHTR -> score=30.0, label=0, level=low
[baseline] Analyzing companies:  86% 6/7 [03:08<00:31, 31.16s/company]03:11:55 [INFO] src.models.baseline_agent: [baseline] Analyzing Kraft Heinz (KHC).
03:12:23 [INFO] src.models.baseline_agent: [baseline] KHC -> score=35.0, label=0, level=low
[baseline] Analyzing companies: 100% 7/7 [03:36<00:00, 30.96s/company]
03:12:23 [INFO] src.models.baseline_agent: [baseline] Predictions saved to '/content/MLOps-group-10/data/results/baseline_predictions.csv'.
  PREDICTIONS SUMMARY  (approach: baseline)
  Ticker    Company                          Score  Label  Level
  --------------------------------------------------------------------
  JNJ       Johnson & Johnson                 20.0      0  low
  DAL       Delta Air Lines                   30.0      0  low
  F         Ford Motor Company                35.0      0  low
  AMZN      Amazon                            30.0      0  low
  KMX       Carmax                            30.0      0  low
  CHTR      Charter Communications            30.0      0  low
  KHC       Kraft Heinz                       35.0      0  low
  Avg score: 30.0  |  High: 0  Medium: 0  Low: 7
Results saved to: /content/MLOps-group-10/data/results/baseline_fold1_test.csv

Running baseline inference for fold 2 (test split)...
03:12:27 [INFO] run_inference_all: Starting inference: approach=baseline, mock=False.
03:12:27 [INFO] numexpr.utils: NumExpr defaulting to 2 threads.
03:12:28 [INFO] run_inference_all: Loaded 7 companies for fold 2 split 'test'.
03:12:30 [INFO] run_inference_all: Loading model 'mistralai/Mistral-7B-Instruct-v0.2' (quantize=True).
03:12:37 [INFO] src.models.base_loader: HF_TOKEN found — using authenticated HuggingFace download.
03:12:37 [INFO] src.models.base_loader: Loading tokenizer for 'mistralai/Mistral-7B-Instruct-v0.2'.
03:12:37 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
03:12:37 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
03:12:37 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
03:12:37 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
03:12:37 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
03:12:37 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
03:12:38 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
03:12:38 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
03:12:38 [INFO] src.models.base_loader: 4-bit NF4 quantisation enabled.
03:12:38 [INFO] src.models.base_loader: Loading model 'mistralai/Mistral-7B-Instruct-v0.2' (device_map='auto').
03:12:38 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
03:12:38 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
03:12:39 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
03:12:39 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 291/291 [00:58<00:00,  4.95it/s, Materializing param=model.norm.weight]
03:13:42 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
03:13:42 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
03:13:42 [INFO] src.models.base_loader: Model loaded and set to eval mode.
[baseline] Analyzing companies:   0% 0/7 [00:00<?, ?company/s]03:13:42 [INFO] src.models.baseline_agent: [baseline] Analyzing American Airlines (AAL).
03:14:03 [INFO] src.models.baseline_agent: [baseline] AAL -> score=45.0, label=0, level=medium
[baseline] Analyzing companies:  14% 1/7 [00:21<02:09, 21.59s/company]03:14:03 [INFO] src.models.baseline_agent: [baseline] Analyzing T-Mobile US (TMUS).
03:14:32 [INFO] src.models.baseline_agent: [baseline] TMUS -> score=30.0, label=0, level=low
[baseline] Analyzing companies:  29% 2/7 [00:49<02:07, 25.50s/company]03:14:32 [INFO] src.models.baseline_agent: [baseline] Analyzing Elevance Health (ELV).
03:14:56 [INFO] src.models.baseline_agent: [baseline] ELV -> score=30.0, label=0, level=low
[baseline] Analyzing companies:  43% 3/7 [01:14<01:40, 25.16s/company]03:14:56 [WARNING] src.models.baseline_agent: [baseline] Sections file not found: /content/MLOps-group-10/data/processed/IP_sections.json
03:14:56 [INFO] src.models.baseline_agent: [baseline] Analyzing International Paper (IP).
03:15:22 [INFO] src.models.baseline_agent: [baseline] IP -> score=30.0, label=0, level=low
[baseline] Analyzing companies:  57% 4/7 [01:40<01:16, 25.46s/company]03:15:22 [INFO] src.models.baseline_agent: [baseline] Analyzing Flutter Entertainment (FLUT).
03:15:48 [INFO] src.models.baseline_agent: [baseline] FLUT -> score=30.0, label=0, level=low
[baseline] Analyzing companies:  71% 5/7 [02:06<00:51, 25.55s/company]03:15:48 [INFO] src.models.baseline_agent: [baseline] Analyzing Texas Instruments (TXN).
03:16:20 [INFO] src.models.baseline_agent: [baseline] TXN -> score=30.0, label=0, level=low
[baseline] Analyzing companies:  86% 6/7 [02:38<00:27, 27.68s/company]03:16:20 [INFO] src.models.baseline_agent: [baseline] Analyzing Fannie Mae (FNMA).
03:16:49 [INFO] src.models.baseline_agent: [baseline] FNMA -> score=30.0, label=0, level=low
[baseline] Analyzing companies: 100% 7/7 [03:06<00:00, 26.70s/company]
03:16:49 [INFO] src.models.baseline_agent: [baseline] Predictions saved to '/content/MLOps-group-10/data/results/baseline_predictions.csv'.
  PREDICTIONS SUMMARY  (approach: baseline)
  Ticker    Company                          Score  Label  Level
  --------------------------------------------------------------------
  AAL       American Airlines                 45.0      0  medium
  TMUS      T-Mobile US                       30.0      0  low
  ELV       Elevance Health                   30.0      0  low
  IP        International Paper               30.0      0  low
  FLUT      Flutter Entertainment             30.0      0  low
  TXN       Texas Instruments                 30.0      0  low
  FNMA      Fannie Mae                        30.0      0  low
  Avg score: 32.1  |  High: 0  Medium: 1  Low: 6
Results saved to: /content/MLOps-group-10/data/results/baseline_fold2_test.csv

Running baseline inference for fold 3 (test split)...
03:16:53 [INFO] run_inference_all: Starting inference: approach=baseline, mock=False.
03:16:53 [INFO] numexpr.utils: NumExpr defaulting to 2 threads.
03:16:53 [INFO] run_inference_all: Loaded 6 companies for fold 3 split 'test'.
03:16:56 [INFO] run_inference_all: Loading model 'mistralai/Mistral-7B-Instruct-v0.2' (quantize=True).
03:17:01 [INFO] src.models.base_loader: HF_TOKEN found — using authenticated HuggingFace download.
03:17:01 [INFO] src.models.base_loader: Loading tokenizer for 'mistralai/Mistral-7B-Instruct-v0.2'.
03:17:02 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
03:17:02 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
03:17:02 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
03:17:02 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
03:17:02 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
03:17:02 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
03:17:02 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
03:17:03 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
03:17:03 [INFO] src.models.base_loader: 4-bit NF4 quantisation enabled.
03:17:03 [INFO] src.models.base_loader: Loading model 'mistralai/Mistral-7B-Instruct-v0.2' (device_map='auto').
03:17:03 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
03:17:03 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
03:17:04 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
03:17:04 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 291/291 [01:00<00:00,  4.79it/s, Materializing param=model.norm.weight]
03:18:09 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
03:18:09 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
03:18:09 [INFO] src.models.base_loader: Model loaded and set to eval mode.
[baseline] Analyzing companies:   0% 0/6 [00:00<?, ?company/s]03:18:09 [INFO] src.models.baseline_agent: [baseline] Analyzing Verizon (VZ).
03:18:34 [INFO] src.models.baseline_agent: [baseline] VZ -> score=30.0, label=0, level=low
[baseline] Analyzing companies:  17% 1/6 [00:24<02:02, 24.59s/company]03:18:34 [INFO] src.models.baseline_agent: [baseline] Analyzing Alphabet (GOOGL).
03:19:02 [INFO] src.models.baseline_agent: [baseline] GOOGL -> score=20.0, label=0, level=low
[baseline] Analyzing companies:  33% 2/6 [00:53<01:48, 27.01s/company]03:19:02 [INFO] src.models.baseline_agent: [baseline] Analyzing Caterpillar (CAT).
03:19:28 [INFO] src.models.baseline_agent: [baseline] CAT -> score=30.0, label=0, level=low
[baseline] Analyzing companies:  50% 3/6 [01:19<01:19, 26.48s/company]03:19:28 [INFO] src.models.baseline_agent: [baseline] Analyzing Micron Technology (MU).
03:19:55 [INFO] src.models.baseline_agent: [baseline] MU -> score=30.0, label=0, level=low
[baseline] Analyzing companies:  67% 4/6 [01:46<00:53, 26.80s/company]03:19:55 [INFO] src.models.baseline_agent: [baseline] Analyzing Alexandria Real Estate Equities (ARE).
03:20:29 [INFO] src.models.baseline_agent: [baseline] ARE -> score=30.0, label=0, level=low
[baseline] Analyzing companies:  83% 5/6 [02:19<00:29, 29.23s/company]03:20:29 [INFO] src.models.baseline_agent: [baseline] Analyzing Paramount Skydance (PARA).
03:21:08 [INFO] src.models.baseline_agent: [baseline] PARA -> score=30.0, label=0, level=low
[baseline] Analyzing companies: 100% 6/6 [02:58<00:00, 29.80s/company]
03:21:08 [INFO] src.models.baseline_agent: [baseline] Predictions saved to '/content/MLOps-group-10/data/results/baseline_predictions.csv'.
  PREDICTIONS SUMMARY  (approach: baseline)
  Ticker    Company                          Score  Label  Level
  --------------------------------------------------------------------
  VZ        Verizon                           30.0      0  low
  GOOGL     Alphabet                          20.0      0  low
  CAT       Caterpillar                       30.0      0  low
  MU        Micron Technology                 30.0      0  low
  ARE       Alexandria Real Estate Equitie    30.0      0  low
  PARA      Paramount Skydance                30.0      0  low
  Avg score: 28.3  |  High: 0  Medium: 0  Low: 6
Results saved to: /content/MLOps-group-10/data/results/baseline_fold3_test.csv

Running baseline inference for fold 4 (test split)...
03:21:12 [INFO] run_inference_all: Starting inference: approach=baseline, mock=False.
03:21:12 [INFO] numexpr.utils: NumExpr defaulting to 2 threads.
03:21:13 [INFO] run_inference_all: Loaded 6 companies for fold 4 split 'test'.
03:21:15 [INFO] run_inference_all: Loading model 'mistralai/Mistral-7B-Instruct-v0.2' (quantize=True).
03:21:21 [INFO] src.models.base_loader: HF_TOKEN found — using authenticated HuggingFace download.
03:21:21 [INFO] src.models.base_loader: Loading tokenizer for 'mistralai/Mistral-7B-Instruct-v0.2'.
03:21:21 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
03:21:21 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
03:21:21 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
03:21:21 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
03:21:22 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"

In [8]:
import pandas as pd
import glob

files = glob.glob("/content/MLOps-group-10/data/results/baseline_fold*_test.csv")
df = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)

print("Rows:", len(df))
print("\nPredicted label counts:")
print(df["predicted_label"].value_counts(dropna=False))

print("\nMax score:", df["predicted_score"].max())

print("\nAny positives?")
print(df[df["predicted_label"] == 1][
    ["ticker","company_name","predicted_score","risk_level"]
])

Rows: 32

Predicted label counts:
predicted_label
0    32
Name: count, dtype: int64

Max score: 50.0

Any positives?
Empty DataFrame
Columns: [ticker, company_name, predicted_score, risk_level]
Index: []

In [12]:
import os
import glob
import pandas as pd
from IPython.display import display

def style_risk_level(val):
    """Color cells based on risk level."""
    color = {
        "low": "background-color: #c6efce; color: #006100",      # green
        "medium": "background-color: #ffeb9c; color: #9c6500",   # yellow
        "high": "background-color: #ffc7ce; color: #9c0006",     # red
    }.get(str(val).lower(), "")
    return color

# Path pattern for all baseline fold prediction files
baseline_pattern = "/content/MLOps-group-10/data/results/baseline_fold*_test.csv"
baseline_files = glob.glob(baseline_pattern)

if baseline_files:
    baseline_df = pd.concat([pd.read_csv(f) for f in baseline_files], ignore_index=True)
    display_cols = [col for col in ["ticker", "company_name", "predicted_score", "predicted_label", "risk_level"] if col in baseline_df.columns]

    print(f"Baseline predictions: {len(baseline_df)} companies (cross-validation)")
    display(
        baseline_df[display_cols].style
        .applymap(style_risk_level, subset=["risk_level"] if "risk_level" in baseline_df.columns else [])
        .format({"predicted_score": "{:.1f}"})
        .set_caption("Baseline Inference Results (Cross-Validation)")
    )

    # Read ground truth
    labels_path = "/content/MLOps-group-10/data/labels/company_labels.csv"
    labels_df = pd.read_csv(labels_path)

    # Merge predictions with ground truth
    merged = baseline_df.merge(labels_df, on="ticker", suffixes=("_pred", "_true"))

    # Figure out which company_name column to use
    company_name_col = "company_name"
    if company_name_col not in merged.columns:
        company_name_col = [col for col in merged.columns if "company_name" in col]
        company_name_col = company_name_col[0] if company_name_col else None

    display_cols = ["ticker"]
    if company_name_col:
        display_cols.append(company_name_col)
    display_cols += ["predicted_label", "label"]

    print(f"Baseline predictions vs Ground Truth: {len(merged)} companies")
    display(
        merged[display_cols]
        .rename(columns={company_name_col: "Company Name", "predicted_label": "Predicted", "label": "Ground Truth"})
        .style.set_caption("Baseline Predictions vs Ground Truth")
    )

    # Example: Calculate accuracy
    accuracy = (merged["predicted_label"] == merged["label"]).mean()
    print(f"Accuracy: {accuracy:.2%}")

else:
    print(f"No baseline prediction files found matching {baseline_pattern}.")

Baseline predictions: 32 companies (cross-validation)

/tmp/ipykernel_4660/4168392740.py:26: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  .applymap(style_risk_level, subset=["risk_level"] if "risk_level" in baseline_df.columns else [])

Baseline predictions vs Ground Truth: 32 companies

Accuracy: 81.25%

In [14]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [19]:
# Verify adapter weights exist for LoRA r32 fold 1
import os
adapter_dir = "/content/MLOps-group-10/data/models/lora_adapter_r32/fold_1/lora_config_r32/final_adapter"
if os.path.isdir(adapter_dir):
    files = os.listdir(adapter_dir)
    print(f"Contents of {adapter_dir}:")
    for f in sorted(files):
        size_mb = os.path.getsize(os.path.join(adapter_dir, f)) / 1e6
        print(f"  {f}  ({size_mb:.2f} MB)")
    if any(f.endswith(".bin") or f.endswith(".safetensors") for f in files):
        print("\n✅ LoRA adapter weights found!")
    else:
        print("\n❌ No adapter weights (.bin or .safetensors) found!")
else:
    print(f"Directory not found: {adapter_dir}")

Contents of /content/MLOps-group-10/data/models/lora_adapter_r32/fold_1/lora_config_r32/final_adapter:
  README.md  (0.01 MB)
  adapter_config.json  (0.00 MB)
  adapter_model.safetensors  (260.10 MB)
  chat_template.jinja  (0.00 MB)
  tokenizer.json  (3.51 MB)
  tokenizer_config.json  (0.00 MB)

✅ LoRA adapter weights found!

---
## Section 5: RAG Inference

Run credit risk inference using **Retrieval-Augmented Generation (RAG)**.

- The FAISS index (built from chunked 10-K text) is used to retrieve the most relevant passages for each company
- Retrieved context is prepended to the prompt before calling Mistral-7B
- This typically improves grounding compared to baseline (less hallucination)

The same quantized model from Section 4 is reused (Colab caches the weights).

In [8]:
for fold in range(1, 6):
    print(f"Running RAG inference for fold {fold} (test split)...")
    !python3 scripts/run_inference_all.py --approach rag --fold {fold} --split test

Running RAG inference for fold 1 (test split)...
04:18:28 [INFO] run_inference_all: Starting inference: approach=rag, mock=False.
04:18:28 [INFO] numexpr.utils: NumExpr defaulting to 2 threads.
04:18:28 [INFO] run_inference_all: Loaded 7 companies for fold 1 split 'test'.
04:18:31 [INFO] run_inference_all: Loading model 'mistralai/Mistral-7B-Instruct-v0.2' (quantize=True).
04:18:41 [INFO] src.models.base_loader: HF_TOKEN found — using authenticated HuggingFace download.
04:18:41 [INFO] src.models.base_loader: Loading tokenizer for 'mistralai/Mistral-7B-Instruct-v0.2'.
04:18:41 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
04:18:41 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
04:18:41 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
04:18:41 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
04:18:41 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
04:18:41 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
04:18:41 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
04:18:41 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
04:18:42 [INFO] src.models.base_loader: 4-bit NF4 quantisation enabled.
04:18:42 [INFO] src.models.base_loader: Loading model 'mistralai/Mistral-7B-Instruct-v0.2' (device_map='auto').
04:18:42 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
04:18:42 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
04:18:42 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
04:18:42 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
04:18:47 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
04:18:47 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/model.safetensors.index.json "HTTP/1.1 307 Temporary Redirect"
04:18:47 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/model.safetensors.index.json "HTTP/1.1 200 OK"
04:18:47 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/model.safetensors.index.json "HTTP/1.1 200 OK"
model.safetensors.index.json: 25.1kB [00:00, 69.6MB/s]
04:18:47 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/revision/main "HTTP/1.1 200 OK"
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 3 files:   0% 0/3 [00:00<?, ?it/s]04:18:47 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/63a8b081895390a26e140280378bc85ec8bce07a/model-00001-of-00003.safetensors "HTTP/1.1 302 Found"
04:18:47 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/63a8b081895390a26e140280378bc85ec8bce07a/model-00002-of-00003.safetensors "HTTP/1.1 302 Found"
04:18:47 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/63a8b081895390a26e140280378bc85ec8bce07a/model-00003-of-00003.safetensors "HTTP/1.1 302 Found"
04:18:47 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/xet-read-token/63a8b081895390a26e140280378bc85ec8bce07a "HTTP/1.1 200 OK"
Downloading (incomplete total...):   0% 0.00/4.94G [00:00<?, ?B/s]04:18:47 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/xet-read-token/63a8b081895390a26e140280378bc85ec8bce07a "HTTP/1.1 200 OK"
Downloading (incomplete total...):   0% 0.00/9.94G [00:00<?, ?B/s]04:18:47 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/xet-read-token/63a8b081895390a26e140280378bc85ec8bce07a "HTTP/1.1 200 OK"
Downloading (incomplete total...):  89% 12.9G/14.5G [03:24<00:19, 82.8MB/s]
Downloading (incomplete total...): 100% 14.5G/14.5G [03:29<00:00, 143MB/s]
Fetching 3 files: 100% 3/3 [03:29<00:00, 69.87s/it]
Download complete: 100% 14.5G/14.5G [03:29<00:00, 69.0MB/s]
Loading weights: 100% 291/291 [00:58<00:00,  4.97it/s, Materializing param=model.norm.weight]
04:23:16 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
04:23:16 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
04:23:17 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
generation_config.json: 100% 111/111 [00:00<00:00, 381kB/s]
04:23:17 [INFO] src.models.base_loader: Model loaded and set to eval mode.
04:23:17 [INFO] src.embeddings.embedder: Loading embedding model 'BAAI/bge-base-en-v1.5' on device 'cpu'
04:23:18 [INFO] datasets: TensorFlow version 2.19.0 available.
04:23:18 [INFO] datasets: JAX version 0.7.2 available.
04:23:23 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
04:23:23 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/modules.json "HTTP/1.1 200 OK"
04:23:23 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/modules.json "HTTP/1.1 200 OK"
modules.json: 100% 349/349 [00:00<00:00, 2.22MB/s]
04:23:23 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
04:23:23 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/config_sentence_transformers.json "HTTP/1.1 200 OK"
04:23:23 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/config_sentence_transformers.json "HTTP/1.1 200 OK"
config_sentence_transformers.json: 100% 124/124 [00:00<00:00, 826kB/s]
04:23:23 [INFO] sentence_transformers.base.model: Loading SentenceTransformer model from BAAI/bge-base-en-v1.5.
04:23:23 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
04:23:23 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/config_sentence_transformers.json "HTTP/1.1 200 OK"
04:23:23 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
04:23:23 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/README.md "HTTP/1.1 200 OK"
04:23:23 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/README.md "HTTP/1.1 200 OK"
README.md: 94.6kB [00:00, 23.4MB/s]
04:23:23 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
04:23:23 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/modules.json "HTTP/1.1 200 OK"
04:23:23 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
04:23:23 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/sentence_bert_config.json "HTTP/1.1 200 OK"
04:23:23 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/sentence_bert_config.json "HTTP/1.1 200 OK"
sentence_bert_config.json: 100% 52.0/52.0 [00:00<00:00, 343kB/s]
04:23:23 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
04:23:23 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
04:23:24 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/config.json "HTTP/1.1 200 OK"
04:23:24 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/config.json "HTTP/1.1 200 OK"
config.json: 100% 777/777 [00:00<00:00, 5.06MB/s]
04:23:24 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
04:23:24 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/config.json "HTTP/1.1 200 OK"
04:23:24 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/model.safetensors "HTTP/1.1 302 Found"
04:23:24 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-base-en-v1.5/xet-read-token/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a "HTTP/1.1 200 OK"
model.safetensors: 100% 438M/438M [00:02<00:00, 175MB/s]
Loading weights: 100% 199/199 [00:00<00:00, 1391.12it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: BAAI/bge-base-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
04:23:27 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
04:23:27 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
04:23:27 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
04:23:27 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
04:23:27 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
04:23:27 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/tokenizer_config.json "HTTP/1.1 200 OK"
04:23:27 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/tokenizer_config.json "HTTP/1.1 200 OK"
tokenizer_config.json: 100% 366/366 [00:00<00:00, 1.51MB/s]
04:23:27 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
04:23:27 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/config.json "HTTP/1.1 200 OK"
04:23:27 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
04:23:27 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/config.json "HTTP/1.1 200 OK"
04:23:28 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
04:23:28 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/tokenizer_config.json "HTTP/1.1 200 OK"
04:23:28 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-base-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
04:23:28 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-base-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
04:23:28 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/vocab.txt "HTTP/1.1 307 Temporary Redirect"
04:23:28 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/vocab.txt "HTTP/1.1 200 OK"
04:23:28 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/vocab.txt "HTTP/1.1 200 OK"
vocab.txt: 232kB [00:00, 18.3MB/s]
04:23:28 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/tokenizer.json "HTTP/1.1 307 Temporary Redirect"
04:23:28 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/tokenizer.json "HTTP/1.1 200 OK"
04:23:28 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/tokenizer.json "HTTP/1.1 200 OK"
tokenizer.json: 711kB [00:00, 67.5MB/s]
04:23:28 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
04:23:28 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/special_tokens_map.json "HTTP/1.1 307 Temporary Redirect"
04:23:28 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/special_tokens_map.json "HTTP/1.1 200 OK"
04:23:28 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/special_tokens_map.json "HTTP/1.1 200 OK"
special_tokens_map.json: 100% 125/125 [00:00<00:00, 890kB/s]
04:23:28 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
04:23:29 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
04:23:29 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
04:23:29 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
config.json: 100% 190/190 [00:00<00:00, 1.30MB/s]
04:23:29 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-base-en-v1.5 "HTTP/1.1 200 OK"
/content/MLOps-group-10/src/embeddings/embedder.py:55: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  return self._model.get_sentence_embedding_dimension()  # type: ignore[return-value]
04:23:29 [INFO] src.embeddings.embedder: Embedding model loaded (dim=768).
04:23:29 [INFO] faiss.loader: Loading faiss with AVX512 support.
04:23:29 [INFO] faiss.loader: Successfully loaded faiss with AVX512 support.
04:23:29 [INFO] src.embeddings.faiss_store: FAISS index loaded from '/content/MLOps-group-10/data/embeddings/faiss.index': 1272 vectors, dimension=768.
04:23:29 [INFO] src.embeddings.faiss_store: Chunk metadata loaded from '/content/MLOps-group-10/data/embeddings/chunk_metadata.json': 1272 entries.
[rag] Analyzing companies:   0% 0/7 [00:00<?, ?it/s]04:23:29 [INFO] src.models.rag_agent: [rag] Retrieving chunks for Johnson & Johnson (JNJ).

Batches:   0% 0/1 [00:00<?, ?it/s]
Batches: 100% 1/1 [00:00<00:00,  3.13it/s]
04:23:29 [INFO] src.models.rag_agent: [rag] Retrieved 100 raw candidates for JNJ.
04:23:29 [INFO] src.models.rag_agent: [rag] 17 chunks after ticker filter.
04:23:29 [INFO] src.models.rag_agent: [rag] 17 chunks after section filter.
04:23:29 [INFO] src.models.rag_agent: [rag] 17 chunks after text filter.
04:23:29 [INFO] src.models.rag_agent: [rag] Using 7 chunks for JNJ.
04:24:01 [WARNING] src.prompts.rag_prompt: Weak prediction (score=50) — likely low signal.
04:24:01 [INFO] src.models.rag_agent: [rag] JNJ -> score=50.0, label=0, level=medium
[rag] Analyzing companies:  14% 1/7 [00:31<03:09, 31.64s/it]04:24:01 [INFO] src.models.rag_agent: [rag] Retrieving chunks for Delta Air Lines (DAL).

Batches:   0% 0/1 [00:00<?, ?it/s]
Batches: 100% 1/1 [00:00<00:00,  6.63it/s]
04:24:01 [INFO] src.models.rag_agent: [rag] Retrieved 100 raw candidates for DAL.
04:24:01 [INFO] src.models.rag_agent: [rag] 35 chunks after ticker filter.
04:24:01 [INFO] src.models.rag_agent: [rag] 35 chunks after section filter.
04:24:01 [INFO] src.models.rag_agent: [rag] 35 chunks after text filter.
04:24:01 [INFO] src.models.rag_agent: [rag] Using 7 chunks for DAL.
04:24:44 [WARNING] src.prompts.rag_prompt: Weak prediction (score=50) — likely low signal.
04:24:44 [INFO] src.models.rag_agent: [rag] DAL -> score=50.0, label=0, level=medium
[rag] Analyzing companies:  29% 2/7 [01:15<03:14, 38.82s/it]04:24:44 [INFO] src.models.rag_agent: [rag] Retrieving chunks for Ford Motor Company (F).

Batches:   0% 0/1 [00:00<?, ?it/s]
Batches: 100% 1/1 [00:00<00:00,  6.72it/s]
04:24:45 [INFO] src.models.rag_agent: [rag] Retrieved 100 raw candidates for F.
04:24:45 [INFO] src.models.rag_agent: [rag] 80 chunks after ticker filter.
04:24:45 [INFO] src.models.rag_agent: [rag] 80 chunks after section filter.
04:24:45 [INFO] src.models.rag_agent: [rag] 80 chunks after text filter.
04:24:45 [INFO] src.models.rag_agent: [rag] Using 7 chunks for F.
04:25:42 [WARNING] src.prompts.rag_prompt: Weak prediction (score=50) — likely low signal.
04:25:42 [INFO] src.models.rag_agent: [rag] F -> score=75.0, label=1, level=high

In [11]:
import os
import glob
import pandas as pd
from IPython.display import display

def style_risk_level(val):
    color = {
        "low": "background-color: #c6efce; color: #006100",
        "medium": "background-color: #ffeb9c; color: #9c6500",
        "high": "background-color: #ffc7ce; color: #9c0006",
    }.get(str(val).lower(), "")
    return color

# Path pattern for all RAG fold prediction files
rag_pattern = "/content/MLOps-group-10/data/results/rag_fold*_test.csv"
rag_files = glob.glob(rag_pattern)

if rag_files:
    # Concatenate all folds
    rag_df = pd.concat([pd.read_csv(f) for f in rag_files], ignore_index=True)
    display_cols = [col for col in ["ticker", "company_name", "predicted_score", "predicted_label", "risk_level"] if col in rag_df.columns]

    print(f"RAG predictions: {len(rag_df)} companies (cross-validation)")
    display(
        rag_df[display_cols].style
        .applymap(style_risk_level, subset=["risk_level"] if "risk_level" in rag_df.columns else [])
        .format({"predicted_score": "{:.1f}"})
        .set_caption("RAG Inference Results (Cross-Validation)")
    )

    # Read ground truth
    labels_path = "/content/MLOps-group-10/data/labels/company_labels.csv"
    labels_df = pd.read_csv(labels_path)

    # Merge predictions with ground truth
    merged = rag_df.merge(labels_df, on="ticker", suffixes=("_pred", "_true"))

    # Figure out which company_name column to use
    company_name_col = "company_name"
    if company_name_col not in merged.columns:
        company_name_col = [col for col in merged.columns if "company_name" in col]
        company_name_col = company_name_col[0] if company_name_col else None

    display_cols = ["ticker"]
    if company_name_col:
        display_cols.append(company_name_col)
    display_cols += ["predicted_label", "label"]

    print(f"RAG predictions vs Ground Truth: {len(merged)} companies")
    display(
        merged[display_cols]
        .rename(columns={company_name_col: "Company Name", "predicted_label": "Predicted", "label": "Ground Truth"})
        .style.set_caption("RAG Predictions vs Ground Truth")
    )

    # Example: Calculate accuracy
    accuracy = (merged["predicted_label"] == merged["label"]).mean()
    print(f"Accuracy: {accuracy:.2%}")

else:
    print(f"No RAG prediction files found matching {rag_pattern}.")

RAG predictions: 32 companies (cross-validation)

/tmp/ipykernel_4660/1574262559.py:26: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  .applymap(style_risk_level, subset=["risk_level"] if "risk_level" in rag_df.columns else [])

RAG predictions vs Ground Truth: 32 companies

Accuracy: 50.00%

---
## Section 6: Generate Fine-Tune Data

The fine-tuning data (`train.jsonl`, `val.jsonl`, `test.jsonl`) is already committed to the repo and should be present.

This cell re-generates it only if the files are missing or you want a fresh split.
The script creates instruction-tuning examples in the format `{instruction, input, output}` from the 10-K sections and labels.

In [6]:
import os

# Regenerate all folds (run this once after updating your data)
os.system("python3 scripts/generate_finetune_data.py")

512

In [7]:
for fold in range(1, 4):  # Use range(1, 6) for 5 folds, or (1, 4) for 3 folds
    print(f"\nFold {fold}:")
    for split in ["train", "val", "test"]:
        path = f"/content/MLOps-group-10/data/finetune/fold_{fold}/{split}.jsonl"
        if os.path.isfile(path):
            with open(path) as f:
                n = sum(1 for line in f if line.strip())
            print(f"  {split:5s}: {n} examples  ({path})")
        else:
            print(f"  {split:5s}: FILE MISSING")

Fold 1:
  train: 20 examples  (/content/MLOps-group-10/data/finetune/fold_1/train.jsonl)
  val  : 5 examples  (/content/MLOps-group-10/data/finetune/fold_1/val.jsonl)
  test : 7 examples  (/content/MLOps-group-10/data/finetune/fold_1/test.jsonl)

Fold 2:
  train: 20 examples  (/content/MLOps-group-10/data/finetune/fold_2/train.jsonl)
  val  : 5 examples  (/content/MLOps-group-10/data/finetune/fold_2/val.jsonl)
  test : 7 examples  (/content/MLOps-group-10/data/finetune/fold_2/test.jsonl)

Fold 3:
  train: 20 examples  (/content/MLOps-group-10/data/finetune/fold_3/train.jsonl)
  val  : 6 examples  (/content/MLOps-group-10/data/finetune/fold_3/val.jsonl)
  test : 6 examples  (/content/MLOps-group-10/data/finetune/fold_3/test.jsonl)

In [8]:
import json

with open("/content/MLOps-group-10/data/finetune/fold_1/train.jsonl") as f:
    first_example = json.loads(f.readline())
print("Sample training example:")
print(json.dumps(first_example, indent=2)[:1000], "..." if len(json.dumps(first_example)) > 1000 else "")

Sample training example:
{
  "text": "<s>[INST] You are a credit risk analyst specializing in SEC 10-K filings. Your task is to assess the credit risk of a company based on excerpts from its annual report.\n\nAnalyze the provided Risk Factors (Item 1A) and Management Discussion & Analysis (Item 7) sections and return a structured JSON assessment.\n\nYour response MUST be valid JSON with exactly these fields:\n{\n  \"predicted_score\": <float 0-100, where 100 = maximum credit risk>,\n  \"risk_level\": <\"low\" | \"medium\" | \"high\">,\n  \"key_signals\": [<list of up to 5 specific risk signals found in the text>],\n  \"citations\": [<list of up to 3 direct quotes from the source text supporting your assessment>],\n  \"rationale\": \"<one paragraph explaining the overall credit risk assessment>\"\n}\n\nScoring guide:\n  0\u201333  \u2192 low risk    (strong financials, stable business, low debt burden)\n  34\u201366 \u2192 medium risk (mixed signals, moderate leverage, some concerns)\n  67\u2013100 \u2192 high  ...

---
## Section 7: LoRA Fine-Tuning

Fine-tune Mistral-7B using **LoRA (Low-Rank Adaptation)** with 4-bit quantization via QLoRA.

Three configurations are trained and tested first to compare rank vs. performance vs. compute cost:

| Config | Rank `r` | Alpha | Target modules | W&B run |
|--------|----------|-------|---------------|---------|
| `lora_config_r8.yaml` | 8 | 16 | q, v only | `lora-r8` |
| `lora_config.yaml` | 16 | 32 | q, k, v, o | `lora-sft` |
| `lora_config_r32.yaml` | 32 | 64 | q, k, v, o, up, down | `lora-r32` |

All runs use: 3 epochs, batch size 2, grad accum 4, lr 2e-4, cosine scheduler, bf16.

We found that lora-r32 performs the best so selected it to train.

In [17]:
!python scripts/train_lora.py --fold 1 --config configs/lora_config_r32.yaml

2026-04-26 11:28:06 — INFO — __main__ — Loading config from /content/MLOps-group-10/configs/lora_config_r32.yaml
2026-04-26 11:28:06 — INFO — __main__ — Model output directory: /content/MLOps-group-10/data/models/lora_adapter_r32/fold_1/lora_config_r32
2026-04-26 11:28:06 — INFO — __main__ — Preparing model for training...
2026-04-26 11:28:15 — INFO — src.models.lora_trainer — Loading tokenizer from 'mistralai/Mistral-7B-Instruct-v0.2'...
2026-04-26 11:28:15 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:28:15 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:28:15 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:28:15 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-26 11:28:15 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:28:15 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-26 11:28:15 — INFO — httpx — HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-26 11:28:15 — INFO — httpx — HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-26 11:28:15 — INFO — src.models.lora_trainer — Loading model 'mistralai/Mistral-7B-Instruct-v0.2' with 4-bit quantization...
2026-04-26 11:28:15 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:28:15 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:28:15 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:28:15 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 291/291 [00:43<00:00,  6.68it/s, Materializing param=model.norm.weight]
2026-04-26 11:29:03 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:29:03 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
2026-04-26 11:29:03 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
2026-04-26 11:29:03 — INFO — src.models.lora_trainer — Applying prepare_model_for_kbit_training...
2026-04-26 11:29:03 — INFO — src.models.lora_trainer — Applying LoRA adapters: r=32, alpha=64
trainable params: 65,011,712 || all params: 7,306,743,808 || trainable%: 0.8897
2026-04-26 11:29:04 — INFO — __main__ — Loading training data from fold 1: /content/MLOps-group-10/data/finetune/fold_1
2026-04-26 11:29:04 — INFO — datasets — TensorFlow version 2.19.0 available.
2026-04-26 11:29:04 — INFO — datasets — JAX version 0.7.2 available.
2026-04-26 11:29:04 — INFO — src.models.lora_trainer — Loading training data from /content/MLOps-group-10/data/finetune/fold_1/train.jsonl
2026-04-26 11:29:04 — INFO — httpx — HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/json/json.py "HTTP/1.1 200 OK"
Generating train split: 20 examples [00:00, 1969.16 examples/s]
2026-04-26 11:29:05 — INFO — src.models.lora_trainer — Loading validation data from /content/MLOps-group-10/data/finetune/fold_1/val.jsonl
2026-04-26 11:29:05 — INFO — httpx — HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/json/json.py "HTTP/1.1 200 OK"
Generating train split: 5 examples [00:00, 3606.45 examples/s]
2026-04-26 11:29:05 — INFO — src.models.lora_trainer — Loaded 20 train examples, 5 validation examples.
2026-04-26 11:29:05 — INFO — __main__ — Initializing W&B run: project=credit-risk-detection, name=lora-r32
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from WANDB_API_KEY.
wandb: Currently logged in as: pankti0 (pankti0-singapore-university-of-technology-and-design) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
]11;?]11;?wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.
wandb: ⢿ Waiting for wandb.init()...
wandb: ⣻ Waiting for wandb.init()...
wandb: ⣽ Waiting for wandb.init()...
wandb: Tracking run with wandb version 0.25.1
wandb: Run data is saved locally in /content/MLOps-group-10/wandb/run-20260426_112905-1ins11gy
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run lora-r32
wandb: ⭐️ View project at https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection
wandb: 🚀 View run at https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection/runs/1ins11gy
2026-04-26 11:29:11 — INFO — src.utils.wandb_logger — W&B run initialized: project=credit-risk-detection, name=lora-r32, id=1ins11gy
2026-04-26 11:29:11 — INFO — __main__ — Starting training...
2026-04-26 11:29:14 — INFO — src.models.lora_trainer — Starting SFT training: epochs=1, lr=0.0002, batch=2, grad_accum=4
Adding EOS to train dataset: 100% 20/20 [00:00<00:00, 2641.67 examples/s]
Tokenizing train dataset: 100% 20/20 [00:00<00:00, 406.22 examples/s]
Adding EOS to eval dataset: 100% 5/5 [00:00<00:00, 1281.41 examples/s]
Tokenizing eval dataset: 100% 5/5 [00:00<00:00, 354.02 examples/s]
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 2}.
100% 3/3 [04:50<00:00, 90.54s/it] 2026-04-26 11:34:05 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:34:05 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:34:05 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:34:05 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
{'train_runtime': '298', 'train_samples_per_second': '0.067', 'train_steps_per_second': '0.01', 'train_loss': '1.729', 'entropy': '0.9038', 'num_tokens': '1.207e+04', 'mean_token_accuracy': '0.6585', 'epoch': '1'}
100% 3/3 [04:57<00:00, 99.31s/it]
2026-04-26 11:34:12 — INFO — src.models.lora_trainer — Training complete. Saving model to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_1/lora_config_r32
2026-04-26 11:34:13 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:34:13 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:34:13 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:34:13 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:34:14 — INFO — src.models.lora_trainer — Model and tokenizer saved to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_1/lora_config_r32
2026-04-26 11:34:14 — INFO — __main__ — Training complete.
2026-04-26 11:34:14 — INFO — __main__ — Saving final adapter to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_1/lora_config_r32/final_adapter
2026-04-26 11:34:14 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:34:14 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:34:14 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:34:14 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 291/291 [00:00<00:00, 390.48it/s, Materializing param=model.norm.weight]
2026-04-26 11:34:15 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:34:15 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
2026-04-26 11:34:15 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Loading weights: 100% 384/384 [00:00<00:00, 644.29it/s, Materializing param=model.layers.31.self_attn.v_proj.lora_B.default.weight]
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
2026-04-26 11:34:19 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:34:19 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:34:19 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:34:19 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:34:20 — INFO — __main__ — Final adapter saved successfully.
2026-04-26 11:34:20 — INFO — src.utils.wandb_logger — Logged 6 metrics for approach 'lora_training'
2026-04-26 11:34:20 — INFO — __main__ — Final training metrics logged: {'train_examples': 20, 'val_examples': 5, 'num_epochs': 1, 'learning_rate': 0.0002, 'lora_r': 32, 'lora_alpha': 64}
  LORA TRAINING COMPLETE
  Adapter saved to : /content/MLOps-group-10/data/models/lora_adapter_r32/fold_1/lora_config_r32/final_adapter
  Train examples   : 20
  Val examples     : 5
  Epochs           : 1
wandb:
wandb: 🚀 View run lora-r32 at: https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection/runs/1ins11gy
wandb: Find logs at: wandb/run-20260426_112905-1ins11gy/logs

In [24]:
!python scripts/train_lora.py --fold 2 --config configs/lora_config_r32.yaml

2026-04-26 11:43:22 — INFO — __main__ — Loading config from /content/MLOps-group-10/configs/lora_config_r32.yaml
2026-04-26 11:43:22 — INFO — __main__ — Model output directory: /content/MLOps-group-10/data/models/lora_adapter_r32/fold_2/lora_config_r32
2026-04-26 11:43:22 — INFO — __main__ — Preparing model for training...
2026-04-26 11:43:30 — INFO — src.models.lora_trainer — Loading tokenizer from 'mistralai/Mistral-7B-Instruct-v0.2'...
2026-04-26 11:43:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:43:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:43:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:43:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-26 11:43:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:43:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-26 11:43:30 — INFO — httpx — HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-26 11:43:30 — INFO — httpx — HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-26 11:43:30 — INFO — src.models.lora_trainer — Loading model 'mistralai/Mistral-7B-Instruct-v0.2' with 4-bit quantization...
2026-04-26 11:43:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:43:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:43:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:43:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 291/291 [00:43<00:00,  6.65it/s, Materializing param=model.norm.weight]
2026-04-26 11:44:18 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:44:18 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
2026-04-26 11:44:18 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
2026-04-26 11:44:18 — INFO — src.models.lora_trainer — Applying prepare_model_for_kbit_training...
2026-04-26 11:44:18 — INFO — src.models.lora_trainer — Applying LoRA adapters: r=32, alpha=64
trainable params: 65,011,712 || all params: 7,306,743,808 || trainable%: 0.8897
2026-04-26 11:44:19 — INFO — __main__ — Loading training data from fold 2: /content/MLOps-group-10/data/finetune/fold_2
2026-04-26 11:44:19 — INFO — datasets — TensorFlow version 2.19.0 available.
2026-04-26 11:44:19 — INFO — datasets — JAX version 0.7.2 available.
2026-04-26 11:44:19 — INFO — src.models.lora_trainer — Loading training data from /content/MLOps-group-10/data/finetune/fold_2/train.jsonl
2026-04-26 11:44:19 — INFO — httpx — HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/json/json.py "HTTP/1.1 200 OK"
Generating train split: 20 examples [00:00, 1761.94 examples/s]
2026-04-26 11:44:19 — INFO — src.models.lora_trainer — Loading validation data from /content/MLOps-group-10/data/finetune/fold_2/val.jsonl
2026-04-26 11:44:19 — INFO — httpx — HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/json/json.py "HTTP/1.1 200 OK"
Generating train split: 5 examples [00:00, 3413.89 examples/s]
2026-04-26 11:44:20 — INFO — src.models.lora_trainer — Loaded 20 train examples, 5 validation examples.
2026-04-26 11:44:20 — INFO — __main__ — Initializing W&B run: project=credit-risk-detection, name=lora-r32
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from WANDB_API_KEY.
wandb: Currently logged in as: pankti0 (pankti0-singapore-university-of-technology-and-design) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
]11;?]11;?wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.
wandb: ⢿ Waiting for wandb.init()...
wandb: ⣻ Waiting for wandb.init()...
wandb: ⣽ setting up run y3nu7af2 (0.2s)
wandb: Tracking run with wandb version 0.25.1
wandb: Run data is saved locally in /content/MLOps-group-10/wandb/run-20260426_114420-y3nu7af2
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run lora-r32
wandb: ⭐️ View project at https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection
wandb: 🚀 View run at https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection/runs/y3nu7af2
2026-04-26 11:44:26 — INFO — src.utils.wandb_logger — W&B run initialized: project=credit-risk-detection, name=lora-r32, id=y3nu7af2
2026-04-26 11:44:26 — INFO — __main__ — Starting training...
2026-04-26 11:44:29 — INFO — src.models.lora_trainer — Starting SFT training: epochs=1, lr=0.0002, batch=2, grad_accum=4
Adding EOS to train dataset: 100% 20/20 [00:00<00:00, 2597.41 examples/s]
Tokenizing train dataset: 100% 20/20 [00:00<00:00, 378.62 examples/s]
Adding EOS to eval dataset: 100% 5/5 [00:00<00:00, 1305.17 examples/s]
Tokenizing eval dataset: 100% 5/5 [00:00<00:00, 451.22 examples/s]
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 2}.
100% 3/3 [04:58<00:00, 92.29s/it] 2026-04-26 11:49:28 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:49:28 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:49:28 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:49:28 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
{'train_runtime': '299.8', 'train_samples_per_second': '0.067', 'train_steps_per_second': '0.01', 'train_loss': '1.724', 'entropy': '0.9097', 'num_tokens': '1.206e+04', 'mean_token_accuracy': '0.6587', 'epoch': '1'}
100% 3/3 [04:59<00:00, 99.92s/it]
2026-04-26 11:49:29 — INFO — src.models.lora_trainer — Training complete. Saving model to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_2/lora_config_r32
2026-04-26 11:49:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:49:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:49:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:49:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:49:30 — INFO — src.models.lora_trainer — Model and tokenizer saved to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_2/lora_config_r32
2026-04-26 11:49:30 — INFO — __main__ — Training complete.
2026-04-26 11:49:30 — INFO — __main__ — Saving final adapter to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_2/lora_config_r32/final_adapter
2026-04-26 11:49:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:49:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:49:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:49:30 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 291/291 [00:00<00:00, 686.80it/s, Materializing param=model.norm.weight]
2026-04-26 11:49:31 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:49:31 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
2026-04-26 11:49:31 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Loading weights: 100% 384/384 [00:00<00:00, 666.02it/s, Materializing param=model.layers.31.self_attn.v_proj.lora_B.default.weight]
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
2026-04-26 11:49:34 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:49:34 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:49:34 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 11:49:34 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 11:49:35 — INFO — __main__ — Final adapter saved successfully.
2026-04-26 11:49:35 — INFO — src.utils.wandb_logger — Logged 6 metrics for approach 'lora_training'
2026-04-26 11:49:35 — INFO — __main__ — Final training metrics logged: {'train_examples': 20, 'val_examples': 5, 'num_epochs': 1, 'learning_rate': 0.0002, 'lora_r': 32, 'lora_alpha': 64}
  LORA TRAINING COMPLETE
  Adapter saved to : /content/MLOps-group-10/data/models/lora_adapter_r32/fold_2/lora_config_r32/final_adapter
  Train examples   : 20
  Val examples     : 5
  Epochs           : 1
wandb:
wandb: 🚀 View run lora-r32 at: https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection/runs/y3nu7af2
wandb: Find logs at: wandb/run-20260426_114420-y3nu7af2/logs

In [30]:
!python scripts/train_lora.py --fold 3 --config configs/lora_config_r32.yaml

2026-04-26 12:02:36 — INFO — __main__ — Loading config from /content/MLOps-group-10/configs/lora_config_r32.yaml
2026-04-26 12:02:36 — INFO — __main__ — Model output directory: /content/MLOps-group-10/data/models/lora_adapter_r32/fold_3/lora_config_r32
2026-04-26 12:02:36 — INFO — __main__ — Preparing model for training...
2026-04-26 12:02:42 — INFO — src.models.lora_trainer — Loading tokenizer from 'mistralai/Mistral-7B-Instruct-v0.2'...
2026-04-26 12:02:42 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:02:42 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:02:42 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:02:42 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-26 12:02:42 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:02:42 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-26 12:02:42 — INFO — httpx — HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-26 12:02:42 — INFO — httpx — HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-26 12:02:43 — INFO — src.models.lora_trainer — Loading model 'mistralai/Mistral-7B-Instruct-v0.2' with 4-bit quantization...
2026-04-26 12:02:43 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:02:43 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:02:43 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:02:43 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 291/291 [00:50<00:00,  5.74it/s, Materializing param=model.norm.weight]
2026-04-26 12:03:37 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:03:37 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
2026-04-26 12:03:37 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
2026-04-26 12:03:37 — INFO — src.models.lora_trainer — Applying prepare_model_for_kbit_training...
2026-04-26 12:03:37 — INFO — src.models.lora_trainer — Applying LoRA adapters: r=32, alpha=64
trainable params: 65,011,712 || all params: 7,306,743,808 || trainable%: 0.8897
2026-04-26 12:03:38 — INFO — __main__ — Loading training data from fold 3: /content/MLOps-group-10/data/finetune/fold_3
2026-04-26 12:03:38 — INFO — datasets — TensorFlow version 2.19.0 available.
2026-04-26 12:03:38 — INFO — datasets — JAX version 0.7.2 available.
2026-04-26 12:03:39 — INFO — src.models.lora_trainer — Loading training data from /content/MLOps-group-10/data/finetune/fold_3/train.jsonl
2026-04-26 12:03:39 — INFO — httpx — HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/json/json.py "HTTP/1.1 200 OK"
Generating train split: 20 examples [00:00, 1331.48 examples/s]
2026-04-26 12:03:39 — INFO — src.models.lora_trainer — Loading validation data from /content/MLOps-group-10/data/finetune/fold_3/val.jsonl
2026-04-26 12:03:39 — INFO — httpx — HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/json/json.py "HTTP/1.1 200 OK"
Generating train split: 6 examples [00:00, 4307.00 examples/s]
2026-04-26 12:03:39 — INFO — src.models.lora_trainer — Loaded 20 train examples, 6 validation examples.
2026-04-26 12:03:39 — INFO — __main__ — Initializing W&B run: project=credit-risk-detection, name=lora-r32
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from WANDB_API_KEY.
wandb: Currently logged in as: pankti0 (pankti0-singapore-university-of-technology-and-design) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
]11;?]11;?wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.
wandb: ⢿ Waiting for wandb.init()...
wandb: ⣻ Waiting for wandb.init()...
wandb: Tracking run with wandb version 0.25.1
wandb: Run data is saved locally in /content/MLOps-group-10/wandb/run-20260426_120339-y1y8ysbh
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run lora-r32
wandb: ⭐️ View project at https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection
wandb: 🚀 View run at https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection/runs/y1y8ysbh
2026-04-26 12:03:45 — INFO — src.utils.wandb_logger — W&B run initialized: project=credit-risk-detection, name=lora-r32, id=y1y8ysbh
2026-04-26 12:03:45 — INFO — __main__ — Starting training...
2026-04-26 12:03:47 — INFO — src.models.lora_trainer — Starting SFT training: epochs=1, lr=0.0002, batch=2, grad_accum=4
Adding EOS to train dataset: 100% 20/20 [00:00<00:00, 2651.43 examples/s]
Tokenizing train dataset: 100% 20/20 [00:00<00:00, 275.94 examples/s]
Adding EOS to eval dataset: 100% 6/6 [00:00<00:00, 1054.24 examples/s]
Tokenizing eval dataset: 100% 6/6 [00:00<00:00, 341.35 examples/s]
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 2}.
100% 3/3 [05:05<00:00, 93.99s/it] 2026-04-26 12:08:53 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:08:53 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:08:53 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:08:53 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
{'train_runtime': '312.2', 'train_samples_per_second': '0.064', 'train_steps_per_second': '0.01', 'train_loss': '1.713', 'entropy': '0.8992', 'num_tokens': '1.209e+04', 'mean_token_accuracy': '0.6596', 'epoch': '1'}
100% 3/3 [05:12<00:00, 104.05s/it]
2026-04-26 12:09:00 — INFO — src.models.lora_trainer — Training complete. Saving model to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_3/lora_config_r32
2026-04-26 12:09:00 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:09:00 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:09:00 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:09:00 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:09:01 — INFO — src.models.lora_trainer — Model and tokenizer saved to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_3/lora_config_r32
2026-04-26 12:09:01 — INFO — __main__ — Training complete.
2026-04-26 12:09:01 — INFO — __main__ — Saving final adapter to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_3/lora_config_r32/final_adapter
2026-04-26 12:09:01 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:09:01 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:09:01 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:09:01 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 291/291 [00:00<00:00, 726.75it/s, Materializing param=model.norm.weight]
2026-04-26 12:09:02 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:09:02 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
2026-04-26 12:09:02 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Loading weights: 100% 384/384 [00:00<00:00, 652.57it/s, Materializing param=model.layers.31.self_attn.v_proj.lora_B.default.weight]
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
2026-04-26 12:09:05 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:09:05 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:09:05 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:09:05 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:09:09 — INFO — __main__ — Final adapter saved successfully.
2026-04-26 12:09:09 — INFO — src.utils.wandb_logger — Logged 6 metrics for approach 'lora_training'
2026-04-26 12:09:09 — INFO — __main__ — Final training metrics logged: {'train_examples': 20, 'val_examples': 6, 'num_epochs': 1, 'learning_rate': 0.0002, 'lora_r': 32, 'lora_alpha': 64}
  LORA TRAINING COMPLETE
  Adapter saved to : /content/MLOps-group-10/data/models/lora_adapter_r32/fold_3/lora_config_r32/final_adapter
  Train examples   : 20
  Val examples     : 6
  Epochs           : 1
wandb:
wandb: 🚀 View run lora-r32 at: https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection/runs/y1y8ysbh
wandb: Find logs at: wandb/run-20260426_120339-y1y8ysbh/logs

In [31]:
!python scripts/train_lora.py --fold 4 --config configs/lora_config_r32.yaml

2026-04-26 12:09:22 — INFO — __main__ — Loading config from /content/MLOps-group-10/configs/lora_config_r32.yaml
2026-04-26 12:09:22 — INFO — __main__ — Model output directory: /content/MLOps-group-10/data/models/lora_adapter_r32/fold_4/lora_config_r32
2026-04-26 12:09:22 — INFO — __main__ — Preparing model for training...
2026-04-26 12:09:32 — INFO — src.models.lora_trainer — Loading tokenizer from 'mistralai/Mistral-7B-Instruct-v0.2'...
2026-04-26 12:09:32 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:09:32 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:09:32 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:09:32 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-26 12:09:32 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:09:32 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-26 12:09:32 — INFO — httpx — HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-26 12:09:32 — INFO — httpx — HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-26 12:09:32 — INFO — src.models.lora_trainer — Loading model 'mistralai/Mistral-7B-Instruct-v0.2' with 4-bit quantization...
2026-04-26 12:09:32 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:09:32 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:09:32 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:09:32 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 291/291 [00:49<00:00,  5.86it/s, Materializing param=model.norm.weight]
2026-04-26 12:10:27 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:10:27 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
2026-04-26 12:10:27 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
2026-04-26 12:10:27 — INFO — src.models.lora_trainer — Applying prepare_model_for_kbit_training...
2026-04-26 12:10:27 — INFO — src.models.lora_trainer — Applying LoRA adapters: r=32, alpha=64
trainable params: 65,011,712 || all params: 7,306,743,808 || trainable%: 0.8897
2026-04-26 12:10:28 — INFO — __main__ — Loading training data from fold 4: /content/MLOps-group-10/data/finetune/fold_4
2026-04-26 12:10:28 — INFO — datasets — TensorFlow version 2.19.0 available.
2026-04-26 12:10:28 — INFO — datasets — JAX version 0.7.2 available.
2026-04-26 12:10:28 — INFO — src.models.lora_trainer — Loading training data from /content/MLOps-group-10/data/finetune/fold_4/train.jsonl
2026-04-26 12:10:28 — INFO — httpx — HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/json/json.py "HTTP/1.1 200 OK"
Generating train split: 20 examples [00:00, 1434.61 examples/s]
2026-04-26 12:10:28 — INFO — src.models.lora_trainer — Loading validation data from /content/MLOps-group-10/data/finetune/fold_4/val.jsonl
2026-04-26 12:10:28 — INFO — httpx — HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/json/json.py "HTTP/1.1 200 OK"
Generating train split: 6 examples [00:00, 4393.47 examples/s]
2026-04-26 12:10:28 — INFO — src.models.lora_trainer — Loaded 20 train examples, 6 validation examples.
2026-04-26 12:10:28 — INFO — __main__ — Initializing W&B run: project=credit-risk-detection, name=lora-r32
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from WANDB_API_KEY.
wandb: Currently logged in as: pankti0 (pankti0-singapore-university-of-technology-and-design) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
]11;?]11;?wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.
wandb: ⢿ Waiting for wandb.init()...
wandb: ⣻ Waiting for wandb.init()...
wandb: ⣽ Waiting for wandb.init()...
wandb: Tracking run with wandb version 0.25.1
wandb: Run data is saved locally in /content/MLOps-group-10/wandb/run-20260426_121029-07qxrw1q
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run lora-r32
wandb: ⭐️ View project at https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection
wandb: 🚀 View run at https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection/runs/07qxrw1q
2026-04-26 12:10:34 — INFO — src.utils.wandb_logger — W&B run initialized: project=credit-risk-detection, name=lora-r32, id=07qxrw1q
2026-04-26 12:10:34 — INFO — __main__ — Starting training...
2026-04-26 12:10:37 — INFO — src.models.lora_trainer — Starting SFT training: epochs=1, lr=0.0002, batch=2, grad_accum=4
Adding EOS to train dataset: 100% 20/20 [00:00<00:00, 2644.16 examples/s]
Tokenizing train dataset: 100% 20/20 [00:00<00:00, 374.01 examples/s]
Adding EOS to eval dataset: 100% 6/6 [00:00<00:00, 1460.75 examples/s]
Tokenizing eval dataset: 100% 6/6 [00:00<00:00, 445.33 examples/s]
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 2}.
100% 3/3 [05:04<00:00, 93.79s/it] 2026-04-26 12:15:43 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:15:43 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:15:43 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:15:43 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
{'train_runtime': '309.5', 'train_samples_per_second': '0.065', 'train_steps_per_second': '0.01', 'train_loss': '1.724', 'entropy': '0.9073', 'num_tokens': '1.208e+04', 'mean_token_accuracy': '0.6595', 'epoch': '1'}
100% 3/3 [05:09<00:00, 103.15s/it]
2026-04-26 12:15:48 — INFO — src.models.lora_trainer — Training complete. Saving model to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_4/lora_config_r32
2026-04-26 12:15:48 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:15:48 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:15:48 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:15:48 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:15:48 — INFO — src.models.lora_trainer — Model and tokenizer saved to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_4/lora_config_r32
2026-04-26 12:15:48 — INFO — __main__ — Training complete.
2026-04-26 12:15:48 — INFO — __main__ — Saving final adapter to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_4/lora_config_r32/final_adapter
2026-04-26 12:15:48 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:15:48 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:15:48 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:15:48 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 291/291 [00:00<00:00, 749.01it/s, Materializing param=model.norm.weight]
2026-04-26 12:15:49 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:15:49 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
2026-04-26 12:15:49 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Loading weights: 100% 384/384 [00:00<00:00, 648.64it/s, Materializing param=model.layers.31.self_attn.v_proj.lora_B.default.weight]
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
2026-04-26 12:15:52 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:15:52 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:15:52 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:15:52 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:15:53 — INFO — __main__ — Final adapter saved successfully.
2026-04-26 12:15:53 — INFO — src.utils.wandb_logger — Logged 6 metrics for approach 'lora_training'
2026-04-26 12:15:53 — INFO — __main__ — Final training metrics logged: {'train_examples': 20, 'val_examples': 6, 'num_epochs': 1, 'learning_rate': 0.0002, 'lora_r': 32, 'lora_alpha': 64}
  LORA TRAINING COMPLETE
  Adapter saved to : /content/MLOps-group-10/data/models/lora_adapter_r32/fold_4/lora_config_r32/final_adapter
  Train examples   : 20
  Val examples     : 6
  Epochs           : 1
wandb:
wandb: 🚀 View run lora-r32 at: https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection/runs/07qxrw1q
wandb: Find logs at: wandb/run-20260426_121029-07qxrw1q/logs

In [32]:
!python scripts/train_lora.py --fold 5 --config configs/lora_config_r32.yaml

2026-04-26 12:16:06 — INFO — __main__ — Loading config from /content/MLOps-group-10/configs/lora_config_r32.yaml
2026-04-26 12:16:06 — INFO — __main__ — Model output directory: /content/MLOps-group-10/data/models/lora_adapter_r32/fold_5/lora_config_r32
2026-04-26 12:16:06 — INFO — __main__ — Preparing model for training...
2026-04-26 12:16:16 — INFO — src.models.lora_trainer — Loading tokenizer from 'mistralai/Mistral-7B-Instruct-v0.2'...
2026-04-26 12:16:16 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:16:16 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:16:16 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:16:16 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-26 12:16:16 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:16:16 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
2026-04-26 12:16:16 — INFO — httpx — HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-04-26 12:16:16 — INFO — httpx — HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-04-26 12:16:16 — INFO — src.models.lora_trainer — Loading model 'mistralai/Mistral-7B-Instruct-v0.2' with 4-bit quantization...
2026-04-26 12:16:17 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:16:17 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:16:17 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:16:17 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 291/291 [00:50<00:00,  5.80it/s, Materializing param=model.norm.weight]
2026-04-26 12:17:11 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:17:11 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
2026-04-26 12:17:11 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
2026-04-26 12:17:11 — INFO — src.models.lora_trainer — Applying prepare_model_for_kbit_training...
2026-04-26 12:17:11 — INFO — src.models.lora_trainer — Applying LoRA adapters: r=32, alpha=64
trainable params: 65,011,712 || all params: 7,306,743,808 || trainable%: 0.8897
2026-04-26 12:17:12 — INFO — __main__ — Loading training data from fold 5: /content/MLOps-group-10/data/finetune/fold_5
2026-04-26 12:17:12 — INFO — datasets — TensorFlow version 2.19.0 available.
2026-04-26 12:17:12 — INFO — datasets — JAX version 0.7.2 available.
2026-04-26 12:17:12 — INFO — src.models.lora_trainer — Loading training data from /content/MLOps-group-10/data/finetune/fold_5/train.jsonl
2026-04-26 12:17:12 — INFO — httpx — HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/json/json.py "HTTP/1.1 200 OK"
Generating train split: 20 examples [00:00, 1239.65 examples/s]
2026-04-26 12:17:12 — INFO — src.models.lora_trainer — Loading validation data from /content/MLOps-group-10/data/finetune/fold_5/val.jsonl
2026-04-26 12:17:12 — INFO — httpx — HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/json/json.py "HTTP/1.1 200 OK"
Generating train split: 6 examples [00:00, 4235.24 examples/s]
2026-04-26 12:17:12 — INFO — src.models.lora_trainer — Loaded 20 train examples, 6 validation examples.
2026-04-26 12:17:12 — INFO — __main__ — Initializing W&B run: project=credit-risk-detection, name=lora-r32
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from WANDB_API_KEY.
wandb: Currently logged in as: pankti0 (pankti0-singapore-university-of-technology-and-design) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
]11;?]11;?wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.
wandb: ⢿ Waiting for wandb.init()...
wandb: ⣻ Waiting for wandb.init()...
wandb: ⣽ Waiting for wandb.init()...
wandb: Tracking run with wandb version 0.25.1
wandb: Run data is saved locally in /content/MLOps-group-10/wandb/run-20260426_121713-0qak6z4z
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run lora-r32
wandb: ⭐️ View project at https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection
wandb: 🚀 View run at https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection/runs/0qak6z4z
2026-04-26 12:17:18 — INFO — src.utils.wandb_logger — W&B run initialized: project=credit-risk-detection, name=lora-r32, id=0qak6z4z
2026-04-26 12:17:18 — INFO — __main__ — Starting training...
2026-04-26 12:17:20 — INFO — src.models.lora_trainer — Starting SFT training: epochs=1, lr=0.0002, batch=2, grad_accum=4
Adding EOS to train dataset: 100% 20/20 [00:00<00:00, 1857.53 examples/s]
Tokenizing train dataset: 100% 20/20 [00:00<00:00, 319.42 examples/s]
Adding EOS to eval dataset: 100% 6/6 [00:00<00:00, 1008.93 examples/s]
Tokenizing eval dataset: 100% 6/6 [00:00<00:00, 317.45 examples/s]
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 2}.
100% 3/3 [05:05<00:00, 94.16s/it] 2026-04-26 12:22:27 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:22:27 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:22:27 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:22:27 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
{'train_runtime': '310.9', 'train_samples_per_second': '0.064', 'train_steps_per_second': '0.01', 'train_loss': '1.709', 'entropy': '0.9045', 'num_tokens': '1.209e+04', 'mean_token_accuracy': '0.6609', 'epoch': '1'}
100% 3/3 [05:10<00:00, 103.64s/it]
2026-04-26 12:22:32 — INFO — src.models.lora_trainer — Training complete. Saving model to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_5/lora_config_r32
2026-04-26 12:22:32 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:22:32 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:22:32 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:22:32 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:22:33 — INFO — src.models.lora_trainer — Model and tokenizer saved to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_5/lora_config_r32
2026-04-26 12:22:33 — INFO — __main__ — Training complete.
2026-04-26 12:22:33 — INFO — __main__ — Saving final adapter to /content/MLOps-group-10/data/models/lora_adapter_r32/fold_5/lora_config_r32/final_adapter
2026-04-26 12:22:33 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:22:33 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:22:33 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:22:33 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 291/291 [00:00<00:00, 873.86it/s, Materializing param=model.norm.weight]
2026-04-26 12:22:33 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:22:33 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/generation_config.json "HTTP/1.1 200 OK"
2026-04-26 12:22:33 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/custom_generate/generate.py "HTTP/1.1 404 Not Found"
Loading weights: 100% 384/384 [00:00<00:00, 626.34it/s, Materializing param=model.layers.31.self_attn.v_proj.lora_B.default.weight]
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
2026-04-26 12:22:36 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:22:36 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:22:36 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-04-26 12:22:36 — INFO — httpx — HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
2026-04-26 12:22:37 — INFO — __main__ — Final adapter saved successfully.
2026-04-26 12:22:37 — INFO — src.utils.wandb_logger — Logged 6 metrics for approach 'lora_training'
2026-04-26 12:22:37 — INFO — __main__ — Final training metrics logged: {'train_examples': 20, 'val_examples': 6, 'num_epochs': 1, 'learning_rate': 0.0002, 'lora_r': 32, 'lora_alpha': 64}
  LORA TRAINING COMPLETE
  Adapter saved to : /content/MLOps-group-10/data/models/lora_adapter_r32/fold_5/lora_config_r32/final_adapter
  Train examples   : 20
  Val examples     : 6
  Epochs           : 1
wandb:
wandb: 🚀 View run lora-r32 at: https://wandb.ai/pankti0-singapore-university-of-technology-and-design/credit-risk-detection/runs/0qak6z4z
wandb: Find logs at: wandb/run-20260426_121713-0qak6z4z/logs

In [ ]:
# OptionalPull training loss curve from W&B and plot locally
try:
    import wandb
    import matplotlib.pyplot as plt

    api = wandb.Api()
    # Find the most recent lora-sft run
    runs = api.runs("credit-risk-detection", filters={"display_name": "lora-sft"})
    runs = sorted(runs, key=lambda r: r.created_at, reverse=True)

    if runs:
        run = runs[0]
        history = run.history(keys=["train/loss", "eval/loss"], pandas=True)

        if not history.empty:
            fig, ax = plt.subplots(figsize=(8, 4))
            if "train/loss" in history.columns:
                ax.plot(history["train/loss"].dropna(), label="Train loss")
            if "eval/loss" in history.columns:
                ax.plot(history["eval/loss"].dropna(), label="Val loss")
            ax.set_xlabel("Step")
            ax.set_ylabel("Loss")
            ax.set_title("LoRA Fine-Tuning Loss Curve")
            ax.legend()
            plt.tight_layout()
            plt.savefig("/content/MLOps-group-10/data/results/lora_loss_curve.png", dpi=150)
            plt.show()
            print(f"Loss curve saved. Run: {run.name} | URL: {run.url}")
        else:
            print("No loss history found in W&B run (may still be syncing).")
    else:
        print("No W&B runs found for lora-sft. Check your W&B dashboard manually.")
except Exception as e:
    print(f"Could not fetch W&B loss curve: {e}")
    print("Check your W&B dashboard at https://wandb.ai")

---
## Section 8: LoRA Inference

Run inference using the **LoRA fine-tuned adapter** on top of Mistral-7B.

The adapter path defaults to `data/models/lora_adapter/final_adapter`. If training produced a different structure, update `ADAPTER_PATH` below.

In [37]:
import os
import subprocess

LORA_CONFIGS = {
    "lora_r32": "data/models/lora_adapter_r32",
}

folds = [1, 2, 3, 4, 5]

for approach, base_dir in LORA_CONFIGS.items():
    for fold in folds:
        # Build possible adapter paths in order of preference
        config_dir = os.path.join(base_dir, f"fold_{fold}", "lora_config_r32")
        final_adapter_dir = os.path.join(config_dir, "final_adapter")
        # Prefer final_adapter if it exists and contains adapter_config.json
        if os.path.isfile(os.path.join(final_adapter_dir, "adapter_config.json")):
            adapter_path = final_adapter_dir
        elif os.path.isfile(os.path.join(config_dir, "adapter_config.json")):
            adapter_path = config_dir
        else:
            print(f"[SKIP] {approach} fold {fold}: adapter_config.json not found in expected locations")
            continue

        print(f"\nRunning inference for {approach} — adapter: {adapter_path} — fold: {fold}")
        result = subprocess.run([
            "python", "scripts/run_inference_all.py",
            "--approach", approach,
            "--adapter-path", adapter_path,
            "--fold", str(fold),
            "--split", "test"
        ], capture_output=True, text=True)
        print("STDOUT:\n", result.stdout)
        print("STDERR:\n", result.stderr)
        if result.returncode != 0:
            print(f"[ERROR] Inference failed for {approach} fold {fold} (exit code {result.returncode})")

print("Inference runs complete.")

Running inference for lora_r32 — adapter: data/models/lora_adapter_r32/fold_1/lora_config_r32/final_adapter — fold: 1
STDOUT:
   PREDICTIONS SUMMARY  (approach: lora_r32)
  Ticker    Company                          Score  Label  Level
  --------------------------------------------------------------------
  JNJ       Johnson & Johnson                 10.0      0  low
  DAL       Delta Air Lines                    0.0      0  low
  F         Ford Motor Company                35.0      0  low
  AMZN      Amazon                             0.0      0  low
  KMX       Carmax                            35.0      0  low
  CHTR      Charter Communications            35.0      0  low
  KHC       Kraft Heinz                       35.0      0  low
  Avg score: 21.4  |  High: 0  Medium: 0  Low: 7
Results saved to: /content/MLOps-group-10/data/results/lora_r32_fold1_test.csv


STDERR:
 12:27:14 [INFO] run_inference_all: Starting inference: approach=lora_r32, mock=False.
12:27:15 [INFO] numexpr.utils: NumExpr defaulting to 2 threads.
12:27:15 [INFO] run_inference_all: Loaded 7 companies for fold 1 split 'test'.
12:27:17 [INFO] run_inference_all: Loading base model + LoRA adapter from 'data/models/lora_adapter_r32/fold_1/lora_config_r32/final_adapter'.
12:27:24 [INFO] src.models.base_loader: HF_TOKEN found — using authenticated HuggingFace download.
12:27:24 [INFO] src.models.base_loader: Loading tokenizer for 'mistralai/Mistral-7B-Instruct-v0.2'.
12:27:24 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
12:27:24 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
12:27:24 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
12:27:24 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
12:27:24 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
12:27:24 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
12:27:24 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
12:27:24 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
12:27:25 [INFO] src.models.base_loader: 4-bit NF4 quantisation enabled.
12:27:25 [INFO] src.models.base_loader: Loading model 'mistralai/Mistral-7B-Instruct-v0.2' (device_map='auto').
12:27:25 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
12:27:25 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
12:27:25 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
12:27:25 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]
Loading weights:   0%|          | 1/291 [00:00<00:00, 9446.63it/s, Materializing param=lm_head.weight]
Loading weights:   0%|          | 1/291 [00:00<00:00, 4275.54it/s, Materializing param=lm_head.weight]
Loading weights:   1%|          | 2/291 [00:01<04:32,  1.06it/s, Materializing param=lm_head.weight]
Loading weights:   1%|          | 2/291 [00:01<04:32,  1.06it/s, Materializing param=model.embed_tokens.weight]
Loading weights:   1%|          | 2/291 [00:01<04:32,  1.06it/s, Materializing param=model.embed_tokens.weight]
Loading weights:   1%|          | 3/291 [00:01<04:31,  1.06it/s, Materializing param=model.layers.0.input_layernorm.weight]
Loading weights:   1%|          | 3/291 [00:01<04:31,  1.06it/s, Materializing param=model.layers.0.input_layernorm.weight]
Loading weights:   1%|▏         | 4/291 [00:01<04:30,  1.06it/s, Materializing param=model.layers.0.mlp.down_proj.weight]
Loading weights:   1%|▏         | 4/291 [00:01<04:30,  1.06it/s, Materializing param=model.layers.0.mlp.down_proj.weight]
Loading weights:   2%|▏         | 5/291 [00:04<03:55,  1.21it/s, Materializing param=model.layers.0.mlp.down_proj.weight]
Loading weights:   2%|▏         | 5/291 [00:04<03:55,  1.21it/s, Materializing param=model.layers.0.mlp.gate_proj.weight]
Loading weights:   2%|▏         | 5/291 [00:04<03:55,  1.21it/s, Materializing param=model.layers.0.mlp.gate_proj.weight]
Loading weights:   2%|▏         | 6/291 [00:04<03:33,  1.33it/s, Materializing param=model.layers.0.mlp.gate_proj.weight]
Loading weights:   2%|▏         | 6/291 [00:04<03:33,  1.33it/s, Materializing param=model.layers.0.mlp.up_proj.weight]
Loading weights:   2%|▏         | 6/291 [00:04<03:33,  1.33it/s, Materializing param=model.layers.0.mlp.up_proj.weight]
Loading weights:   2%|▏         | 7/291 [00:04<02:54,  1.63it/s, Materializing param=model.layers.0.mlp.up_proj.weight]
Loading weights:   2%|▏         | 7/291 [00:04<02:54,  1.63it/s, Materializing param=model.layers.0.post_attention_layernorm.weight]
Loading weights:   2%|▏         | 7/291 [00:04<02:54,  1.63it/s, Materializing param=model.layers.0.post_attention_layernorm.weight]
Loading weights:   3%|▎         | 8/291 [00:04<02:53,  1.63it/s, Materializing param=model.layers.0.self_attn.k_proj.weight]
Loading weights:   3%|▎         | 8/291 [00:04<02:53,  1.63it/s, Materializing param=model.layers.0.self_attn.k_proj.weight]
Loading weights:   3%|▎         | 9/291 [00:05<02:19,  2.02it/s, Materializing param=model.layers.0.self_attn.k_proj.weight]
Loading weights:   3%|▎         | 9/291 [00:05<02:19,  2.02it/s, Materializing param=model.layers.0.self_attn.o_proj.weight]
Loading weights:   3%|▎         | 9/291 [00:05<02:19,  2.02it/s, Materializing param=model.layers.0.self_attn.o_proj.weight]
Loading weights:   3%|▎         | 10/291 [00:08<04:27,  1.05it/s, Materializing param=model.layers.0.self_attn.o_proj.weight]
Loading weights:   3%|▎         | 10/291 [00:08<04:27,  1.05it/s, Materializing param=model.layers.0.self_attn.q_proj.weight]
Loading weights:   3%|▎         | 10/291 [00:08<04:27,  1.05it/s, Materializing param=model.layers.0.self_attn.q_proj.weight]
Loading weights:   4%|▍         | 11/291 [00:09<04:48,  1.03s/it, Materializing param=model.layers.0.self_attn.q_proj.weight]
Loading weights:   4%|▍         | 11/291 [00:09<04:48,  1.03s/it, Materializing param=model.layers.0.self_attn.v_proj.weight]
Loading weights:   4%|▍         | 11/291 [00:09<04:48,  1.03s/it, Materializing param=model.layers.0.self_attn.v_proj.weight]
Loading weights:   4%|▍         | 12/291 [00:10<05:23,  1.16s/it, Materializing param=model.layers.0.self_attn.v_proj.weight]
Loading weights:   4%|▍         | 12/291 [00:10<05:23,  1.16s/it, Materializing param=model.layers.1.input_layernorm.weight]
Loading weights:   4%|▍         | 12/291 [00:10<05:23,  1.16s/it, Materializing param=model.layers.1.input_layernorm.weight]
Loading weights:   4%|▍         | 13/291 [00:10<05:22,  1.16s/it, Materializing param=model.layers.1.mlp.down_proj.weight]
Loading weights:   4%|▍         | 13/291 [00:10<05:22,  1.16s/it, Materializing param=model.layers.1.mlp.down_proj.weight]
Loading weights:   5%|▍         | 14/291 [00:12<04:50,  1.05s/it, Materializing param=model.layers.1.mlp.down_proj.weight]
Loading weights:   5%|▍         | 14/291 [00:12<04:50,  1.05s/it, Materializing param=model.layers.1.mlp.gate_proj.weight]
Loading weights:   5%|▍         | 14/291 [00:12<04:50,  1.05s/it, Materializing param=model.layers.1.mlp.gate_proj.weight]
Loading weights:   5%|▌         | 15/291 [00:14<05:15,  1.14s/it, Materializing param=model.layers.1.mlp.gate_proj.weight]
Loading weights:   5%|▌         | 15/291 [00:14<05:15,  1.14s/it, Materializing param=model.layers.1.mlp.up_proj.weight]
Loading weights:   5%|▌         | 15/291 [00:14<05:15,  1.14s/it, Materializing param=model.layers.1.mlp.up_proj.weight]
Loading weights:   5%|▌         | 16/291 [00:14<04:51,  1.06s/it, Materializing param=model.layers.1.mlp.up_proj.weight]
Loading weights:   5%|▌         | 16/291 [00:14<04:51,  1.06s/it, Materializing param=model.layers.1.post_attention_layernorm.weight]
Loading weights:   5%|▌         | 16/291 [00:14<04:51,  1.06s/it, Materializing param=model.layers.1.post_attention_layernorm.weight]
Loading weights:   6%|▌         | 17/291 [00:14<04:50,  1.06s/it, Materializing param=model.layers.1.self_attn.k_proj.weight]
Loading weights:   6%|▌         | 17/291 [00:14<04:50,  1.06s/it, Materializing param=model.layers.1.self_attn.k_proj.weight]
Loading weights:   6%|▌         | 18/291 [00:16<04:41,  1.03s/it, Materializing param=model.layers.1.self_attn.k_proj.weight]
Loading weights:   6%|▌         | 18/291 [00:16<04:41,  1.03s/it, Materializing param=model.layers.1.self_attn.o_proj.weight]
Loading weights:   6%|▌         | 18/291 [00:16<04:41,  1.03s/it, Materializing param=model.layers.1.self_attn.o_proj.weight]
Loading weights:   7%|▋         | 19/291 [00:17<04:32,  1.00s/it, Materializing param=model.layers.1.self_attn.o_proj.weight]
Loading weights:   7%|▋         | 19/291 [00:17<04:32,  1.00s/it, Materializing param=model.layers.1.self_attn.q_proj.weight]
Loading weights:   7%|▋         | 19/291 [00:17<04:32,  1.00s/it, Materializing param=model.layers.1.self_attn.q_proj.weight]
Loading weights:   7%|▋         | 20/291 [00:19<05:39,  1.25s/it, Materializing param=model.layers.1.self_attn.q_proj.weight]
Loading weights:   7%|▋         | 20/291 [00:19<05:39,  1.25s/it, Materializing param=model.layers.1.self_attn.v_proj.weight]
Loading weights:   7%|▋         | 20/291 [00:19<05:39,  1.25s/it, Materializing param=model.layers.1.self_attn.v_proj.weight]
Loading weights:   7%|▋         | 21/291 [00:22<07:20,  1.63s/it, Materializing param=model.layers.1.self_attn.v_proj.weight]
Loading weights:   7%|▋         | 21/291 [00:22<07:20,  1.63s/it, Materializing param=model.layers.2.input_layernorm.weight]
Loading weights:   7%|▋         | 21/291 [00:22<07:20,  1.63s/it, Materializing param=model.layers.2.input_layernorm.weight]
Loading weights:   8%|▊         | 22/291 [00:22<07:18,  1.63s/it, Materializing param=model.layers.2.mlp.down_proj.weight]
Loading weights:   8%|▊         | 22/291 [00:22<07:18,  1.63s/it, Materializing param=model.layers.2.mlp.down_proj.weight]
Loading weights:   8%|▊         | 23/291 [00:24<06:18,  1.41s/it, Materializing param=model.layers.2.mlp.down_proj.weight]
Loading weights:   8%|▊         | 23/291 [00:24<06:18,  1.41s/it, Materializing param=model.layers.2.mlp.gate_proj.weight]
Loading weights:   8%|▊         | 23/291 [00:24<06:18,  1.41s/it, Materializing param=model.layers.2.mlp.gate_proj.weight]
Loading weights:   8%|▊         | 24/291 [00:26<06:40,  1.50s/it, Materializing param=model.layers.2.mlp.gate_proj.weight]
Loading weights:   8%|▊         | 24/291 [00:26<06:40,  1.50s/it, Materializing param=model.layers.2.mlp.up_proj.weight]
Loading weights:   8%|▊         | 24/291 [00:26<06:40,  1.50s/it, Materializing param=model.layers.2.mlp.up_proj.weight]
Loading weights:   9%|▊         | 25/291 [00:28<07:14,  1.63s/it, Materializing param=model.layers.2.mlp.up_proj.weight]
Loading weights:   9%|▊         | 25/291 [00:28<07:14,  1.63s/it, Materializing param=model.layers.2.post_attention_layernorm.weight]
Loading weights:   9%|▊         | 25/291 [00:28<07:14,  1.63s/it, Materializing param=model.layers.2.post_attention_layernorm.weight]
Loading weights:   9%|▉         | 26/291 [00:28<07:13,  1.63s/it, Materializing param=model.layers.2.self_attn.k_proj.weight]
Loading weights:   9%|▉         | 26/291 [00:28<07:13,  1.63s/it, Materializing param=model.layers.2.self_attn.k_proj.weight]
Loading weights:   9%|▉         | 27/291 [00:30<05:58,  1.36s/it, Materializing param=model.layers.2.self_attn.k_proj.weight]
Loading weights:   9%|▉         | 27/291 [00:30<05:58,  1.36s/it, Materializing param=model.layers.2.self_attn.o_proj.weight]
Loading weights:   9%|▉         | 27/291 [00:30<05:58,  1.36s/it, Materializing param=model.layers.2.self_attn.o_proj.weight]
Loading weights:  10%|▉         | 28/291 [00:32<06:28,  1.48s/it, Materializing param=model.layers.2.self_attn.o_proj.weight]
Loading weights:  10%|▉         | 28/291 [00:32<06:28,  1.48s/it, Materializing param=model.layers.2.self_attn.q_proj.weight]
Loading weights:  10%|▉         | 28/291 [00:32<06:28,  1.48s/it, Materializing param=model.layers.2.self_attn.q_proj.weight]
Loading weights:  10%|▉         | 29/291 [00:35<07:45,  1.78s/it, Materializing param=model.layers.2.self_attn.q_proj.weight]
Loading weights:  10%|▉         | 29/291 [00:35<07:45,  1.78s/it, Materializing param=model.layers.2.self_attn.v_proj.weight]
Loading weights:  10%|▉         | 29/291 [00:35<07:45,  1.78s/it, Materializing param=model.layers.2.self_attn.v_proj.weight]
Loading weights:  10%|█         | 30/291 [00:35<06:37,  1.52s/it, Materializing param=model.layers.2.self_attn.v_proj.weight]
Loading weights:  10%|█         | 30/291 [00:35<06:37,  1.52s/it, Materializing param=model.layers.3.input_layernorm.weight]
Loading weights:  10%|█         | 30/291 [00:35<06:37,  1.52s/it, Materializing param=model.layers.3.input_layernorm.weight]
Loading weights:  11%|█         | 31/291 [00:35<06:36,  1.52s/it, Materializing param=model.layers.3.mlp.down_proj.weight]
Loading weights:  11%|█         | 31/291 [00:35<06:36,  1.52s/it, Materializing param=model.layers.3.mlp.down_proj.weight]
Loading weights:  11%|█         | 32/291 [00:37<05:21,  1.24s/it, Materializing param=model.layers.3.mlp.down_proj.weight]
Loading weights:  11%|█         | 32/291 [00:37<05:21,  1.24s/it, Materializing param=model.layers.3.mlp.gate_proj.weight]
Loading weights:  11%|█         | 32/291 [00:37<05:21,  1.24s/it, Materializing param=model.layers.3.mlp.gate_proj.weight]
Loading weights:  11%|█▏        | 33/291 [00:39<05:55,  1.38s/it, Materializing param=model.layers.3.mlp.gate_proj.weight]
Loading weights:  11%|█▏        | 33/291 [00:39<05:55,  1.38s/it, Materializing param=model.layers.3.mlp.up_proj.weight]
Loading weights:  11%|█▏        | 33/291 [00:39<05:55,  1.38s/it, Materializing param=model.layers.3.mlp.up_proj.weight]
Loading weights:  12%|█▏        | 34/291 [00:43<08:30,  1.98s/it, Materializing param=model.layers.3.mlp.up_proj.weight]
Loading weights:  12%|█▏        | 34/291 [00:43<08:30,  1.98s/it, Materializing param=model.layers.3.post_attention_layernorm.weight]
Loading weights:  12%|█▏        | 34/291 [00:43<08:30,  1.98s/it, Materializing param=model.layers.3.post_attention_layernorm.weight]
Loading weights:  12%|█▏        | 35/291 [00:43<08:28,  1.98s/it, Materializing param=model.layers.3.self_attn.k_proj.weight]
Loading weights:  12%|█▏        | 35/291 [00:43<08:28,  1.98s/it, Materializing param=model.layers.3.self_attn.k_proj.weight]
Loading weights:  12%|█▏        | 36/291 [00:44<06:23,  1.50s/it, Materializing param=model.layers.3.self_attn.k_proj.weight]
Loading weights:  12%|█▏        | 36/291 [00:44<06:23,  1.50s/it, Materializing param=model.layers.3.self_attn.o_proj.weight]
Loading weights:  12%|█▏        | 36/291 [00:44<06:23,  1.50s/it, Materializing param=model.layers.3.self_attn.o_proj.weight]
Loading weights:  13%|█▎        | 37/291 [00:46<06:47,  1.60s/it, Materializing param=model.layers.3.self_attn.o_proj.weight]
Loading weights:  13%|█▎        | 37/291 [00:46<06:47,  1.60s/it, Materializing param=model.layers.3.self_attn.q_proj.weight]
Loading weights:  13%|█▎        | 37/291 [00:46<06:47,  1.60s/it, Materializing param=model.layers.3.self_attn.q_proj.weight]
Loading weights:  13%|█▎        | 38/291 [00:50<08:22,  1.99s/it, Materializing param=model.layers.3.self_attn.q_proj.weight]
Loading weights:  13%|█▎        | 38/291 [00:50<08:22,  1.99s/it, Materializing param=model.layers.3.self_attn.v_proj.weight]
Loading weights:  13%|█▎        | 38/291 [00:50<08:22,  1.99s/it, Materializing param=model.layers.3.self_attn.v_proj.weight]
Loading weights:  13%|█▎        | 39/291 [00:50<06:32,  1.56s/it, Materializing param=model.layers.3.self_attn.v_proj.weight]
Loading weights:  13%|█▎        | 39/291 [00:50<06:32,  1.56s/it, Materializing param=model.layers.4.input_layernorm.weight]
Loading weights:  13%|█▎        | 39/291 [00:50<06:32,  1.56s/it, Materializing param=model.layers.4.input_layernorm.weight]
Loading weights:  14%|█▎        | 40/291 [00:50<06:31,  1.56s/it, Materializing param=model.layers.4.mlp.down_proj.weight]
Loading weights:  14%|█▎        | 40/291 [00:50<06:31,  1.56s/it, Materializing param=model.layers.4.mlp.down_proj.weight]
Loading weights:  14%|█▍        | 41/291 [00:50<06:29,  1.56s/it, Materializing param=model.layers.4.mlp.gate_proj.weight]
Loading weights:  14%|█▍        | 41/291 [00:50<06:29,  1.56s/it, Materializing param=model.layers.4.mlp.gate_proj.weight]
Loading weights:  14%|█▍        | 42/291 [00:50<06:28,  1.56s/it, Materializing param=model.layers.4.mlp.up_proj.weight]
Loading weights:  14%|█▍        | 42/291 [00:50<06:28,  1.56s/it, Materializing param=model.layers.4.mlp.up_proj.weight]
Loading weights:  15%|█▍        | 43/291 [00:50<06:26,  1.56s/it, Materializing param=model.layers.4.post_attention_layernorm.weight]
Loading weights:  15%|█▍        | 43/291 [00:50<06:26,  1.56s/it, Materializing param=model.layers.4.post_attention_layernorm.weight]
Loading weights:  15%|█▌        | 44/291 [00:50<06:25,  1.56s/it, Materializing param=model.layers.4.self_attn.k_proj.weight]
Loading weights:  15%|█▌        | 44/291 [00:50<06:25,  1.56s/it, Materializing param=model.layers.4.self_attn.k_proj.weight]
Loading weights:  15%|█▌        | 45/291 [00:50<06:23,  1.56s/it, Materializing param=model.layers.4.self_attn.o_proj.weight]
Loading weights:  15%|█▌        | 45/291 [00:50<06:23,  1.56s/it, Materializing param=model.layers.4.self_attn.o_proj.weight]
Loading weights:  16%|█▌        | 46/291 [00:50<06:22,  1.56s/it, Materializing param=model.layers.4.self_attn.q_proj.weight]
Loading weights:  16%|█▌        | 46/291 [00:50<06:22,  1.56s/it, Materializing param=model.layers.4.self_attn.q_proj.weight]
Loading weights:  16%|█▌        | 47/291 [00:50<06:20,  1.56s/it, Materializing param=model.layers.4.self_attn.v_proj.weight]
Loading weights:  16%|█▌        | 47/291 [00:50<06:20,  1.56s/it, Materializing param=model.layers.4.self_attn.v_proj.weight]
Loading weights:  16%|█▋        | 48/291 [00:50<06:18,  1.56s/it, Materializing param=model.layers.5.input_layernorm.weight]
Loading weights:  16%|█▋        | 48/291 [00:50<06:18,  1.56s/it, Materializing param=model.layers.5.input_layernorm.weight]
Loading weights:  17%|█▋        | 49/291 [00:50<06:17,  1.56s/it, Materializing param=model.layers.5.mlp.down_proj.weight]
Loading weights:  17%|█▋        | 49/291 [00:50<06:17,  1.56s/it, Materializing param=model.layers.5.mlp.down_proj.weight]
Loading weights:  17%|█▋        | 50/291 [00:50<06:15,  1.56s/it, Materializing param=model.layers.5.mlp.gate_proj.weight]
Loading weights:  17%|█▋        | 50/291 [00:50<06:15,  1.56s/it, Materializing param=model.layers.5.mlp.gate_proj.weight]

In [44]:
import os
import subprocess

approach = "lora_r32_rag"  # or your actual RAG+LoRA approach name
base_dir = "data/models/lora_adapter_r32"
folds = [1, 2, 3, 4, 5]

for fold in folds:
    config_dir = os.path.join(base_dir, f"fold_{fold}", "lora_config_r32")
    final_adapter_dir = os.path.join(config_dir, "final_adapter")
    # Prefer final_adapter if it exists and contains adapter_config.json
    if os.path.isfile(os.path.join(final_adapter_dir, "adapter_config.json")):
        adapter_path = final_adapter_dir
    elif os.path.isfile(os.path.join(config_dir, "adapter_config.json")):
        adapter_path = config_dir
    else:
        print(f"[SKIP] {approach} fold {fold}: adapter_config.json not found in expected locations")
        continue

    print(f"\nRunning inference for {approach} — adapter: {adapter_path} — fold: {fold}")
    result = subprocess.run([
        "python", "scripts/run_inference_all.py",
        "--approach", approach,
        "--adapter-path", adapter_path,
        "--fold", str(fold),
        "--split", "test"
    ], capture_output=True, text=True)
    print("STDOUT:\n", result.stdout)
    print("STDERR:\n", result.stderr)
    if result.returncode != 0:
        print(f"[ERROR] Inference failed for {approach} fold {fold} (exit code {result.returncode})")

print("Inference runs complete.")

Streaming output truncated to the last 5000 lines.
Loading weights:  99%|█████████▉| 197/199 [00:00<00:00, 548.55it/s, Materializing param=encoder.layer.11.output.dense.weight]
Loading weights:  99%|█████████▉| 197/199 [00:00<00:00, 548.55it/s, Materializing param=encoder.layer.11.output.dense.weight]
Loading weights:  99%|█████████▉| 198/199 [00:00<00:00, 548.55it/s, Materializing param=pooler.dense.bias]
Loading weights:  99%|█████████▉| 198/199 [00:00<00:00, 548.55it/s, Materializing param=pooler.dense.bias]
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 548.55it/s, Materializing param=pooler.dense.weight]
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 548.55it/s, Materializing param=pooler.dense.weight]
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 541.43it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: BAAI/bge-base-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
13:02:53 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
13:02:53 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
13:02:53 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
13:02:53 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
13:02:53 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
13:02:53 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/tokenizer_config.json "HTTP/1.1 200 OK"
13:02:53 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
13:02:53 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/config.json "HTTP/1.1 200 OK"
13:02:53 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
13:02:53 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/config.json "HTTP/1.1 200 OK"
13:02:53 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
13:02:53 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/tokenizer_config.json "HTTP/1.1 200 OK"
13:02:54 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-base-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
13:02:54 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-base-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
13:02:54 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/BAAI/bge-base-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
13:02:54 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-base-en-v1.5/a5beb1e3e68b9ab74eb54cfd186867f64f240e1a/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
13:02:54 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-base-en-v1.5 "HTTP/1.1 200 OK"
/content/MLOps-group-10/src/embeddings/embedder.py:55: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  return self._model.get_sentence_embedding_dimension()  # type: ignore[return-value]
13:02:54 [INFO] src.embeddings.embedder: Embedding model loaded (dim=768).
13:02:54 [INFO] faiss.loader: Loading faiss with AVX512 support.
13:02:54 [INFO] faiss.loader: Successfully loaded faiss with AVX512 support.
13:02:54 [INFO] src.embeddings.faiss_store: FAISS index loaded from '/content/MLOps-group-10/data/embeddings/faiss.index': 1272 vectors, dimension=768.
13:02:54 [INFO] src.embeddings.faiss_store: Chunk metadata loaded from '/content/MLOps-group-10/data/embeddings/chunk_metadata.json': 1272 entries.

[rag] Analyzing companies:   0%|          | 0/7 [00:00<?, ?it/s]13:02:54 [INFO] src.models.rag_agent: [rag] Retrieving chunks for Johnson & Johnson (JNJ).


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches: 100%|██████████| 1/1 [00:01<00:00,  1.95s/it]
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.95s/it]
13:02:56 [INFO] src.models.rag_agent: [rag] Retrieved 100 raw candidates for JNJ.
13:02:56 [INFO] src.models.rag_agent: [rag] 17 chunks after ticker filter.
13:02:56 [INFO] src.models.rag_agent: [rag] 17 chunks after section filter.
13:02:56 [INFO] src.models.rag_agent: [rag] 17 chunks after text filter.
13:02:56 [INFO] src.models.rag_agent: [rag] Using 7 chunks for JNJ.
13:04:23 [WARNING] src.models.rag_agent: [rag] Model did not return JSON. Using fallback.

[rag] Analyzing companies:  14%|█▍        | 1/7 [01:28<08:51, 88.66s/it]13:04:23 [INFO] src.models.rag_agent: [rag] Retrieving chunks for Delta Air Lines (DAL).


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches: 100%|██████████| 1/1 [00:00<00:00,  5.42it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.41it/s]
13:04:23 [INFO] src.models.rag_agent: [rag] Retrieved 100 raw candidates for DAL.
13:04:23 [INFO] src.models.rag_agent: [rag] 35 chunks after ticker filter.
13:04:23 [INFO] src.models.rag_agent: [rag] 35 chunks after section filter.
13:04:23 [INFO] src.models.rag_agent: [rag] 35 chunks after text filter.
13:04:23 [INFO] src.models.rag_agent: [rag] Using 7 chunks for DAL.
13:05:51 [WARNING] src.models.rag_agent: [rag] Model did not return JSON. Using fallback.

[rag] Analyzing companies:  29%|██▊       | 2/7 [02:56<07:22, 88.42s/it]13:05:51 [INFO] src.models.rag_agent: [rag] Retrieving chunks for Ford Motor Company (F).


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches: 100%|██████████| 1/1 [00:00<00:00,  6.31it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
13:05:51 [INFO] src.models.rag_agent: [rag] Retrieved 100 raw candidates for F.
13:05:51 [INFO] src.models.rag_agent: [rag] 80 chunks after ticker filter.
13:05:51 [INFO] src.models.rag_agent: [rag] 80 chunks after section filter.
13:05:51 [INFO] src.models.rag_agent: [rag] 80 chunks after text filter.
13:05:51 [INFO] src.models.rag_agent: [rag] Using 7 chunks for F.
13:07:15 [WARNING] src.models.rag_agent: [rag] Model did not return JSON. Using fallback.

[rag] Analyzing companies:  43%|████▎     | 3/7 [04:21<05:46, 86.58s/it]13:07:15 [INFO] src.models.rag_agent: [rag] Retrieving chunks for Amazon (AMZN).


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches: 100%|██████████| 1/1 [00:00<00:00,  5.89it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.88it/s]
13:07:15 [INFO] src.models.rag_agent: [rag] Retrieved 100 raw candidates for AMZN.
13:07:15 [INFO] src.models.rag_agent: [rag] 0 chunks after ticker filter.
13:07:15 [INFO] src.models.rag_agent: [rag] 0 chunks after section filter.
13:07:15 [INFO] src.models.rag_agent: [rag] 0 chunks after text filter.
13:07:15 [WARNING] src.models.rag_agent: [rag] Too few filtered chunks (0) for AMZN, using top FAISS results.
13:07:15 [INFO] src.models.rag_agent: [rag] Using 7 chunks for AMZN.
13:08:40 [WARNING] src.models.rag_agent: [rag] Model did not return JSON. Using fallback.

[rag] Analyzing companies:  57%|█████▋    | 4/7 [05:46<04:17, 85.90s/it]13:08:40 [INFO] src.models.rag_agent: [rag] Retrieving chunks for Carmax (KMX).


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches: 100%|██████████| 1/1 [00:00<00:00,  4.46it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.45it/s]
13:08:40 [INFO] src.models.rag_agent: [rag] Retrieved 100 raw candidates for KMX.
13:08:40 [INFO] src.models.rag_agent: [rag] 0 chunks after ticker filter.
13:08:40 [INFO] src.models.rag_agent: [rag] 0 chunks after section filter.
13:08:40 [INFO] src.models.rag_agent: [rag] 0 chunks after text filter.
13:08:40 [WARNING] src.models.rag_agent: [rag] Too few filtered chunks (0) for KMX, using top FAISS results.
13:08:40 [INFO] src.models.rag_agent: [rag] Using 7 chunks for KMX.
13:10:06 [WARNING] src.models.rag_agent: [rag] Model did not return JSON. Using fallback.

[rag] Analyzing companies:  71%|███████▏  | 5/7 [07:11<02:51, 85.86s/it]13:10:06 [INFO] src.models.rag_agent: [rag] Retrieving chunks for Charter Communications (CHTR).


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches: 100%|██████████| 1/1 [00:00<00:00,  4.88it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  4.87it/s]
13:10:06 [INFO] src.models.rag_agent: [rag] Retrieved 100 raw candidates for CHTR.
13:10:06 [INFO] src.models.rag_agent: [rag] 0 chunks after ticker filter.
13:10:06 [INFO] src.models.rag_agent: [rag] 0 chunks after section filter.
13:10:06 [INFO] src.models.rag_agent: [rag] 0 chunks after text filter.
13:10:06 [WARNING] src.models.rag_agent: [rag] Too few filtered chunks (0) for CHTR, using top FAISS results.
13:10:06 [INFO] src.models.rag_agent: [rag] Using 7 chunks for CHTR.
13:11:30 [WARNING] src.models.rag_agent: [rag] Model did not return JSON. Using fallback.

[rag] Analyzing companies:  86%|████████▌ | 6/7 [08:36<01:25, 85.33s/it]13:11:30 [INFO] src.models.rag_agent: [rag] Retrieving chunks for Kraft Heinz (KHC).


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches: 100%|██████████| 1/1 [00:00<00:00,  5.12it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  5.11it/s]
13:11:30 [INFO] src.models.rag_agent: [rag] Retrieved 100 raw candidates for KHC.
13:11:30 [INFO] src.models.rag_agent: [rag] 0 chunks after ticker filter.
13:11:30 [INFO] src.models.rag_agent: [rag] 0 chunks after section filter.
13:11:30 [INFO] src.models.rag_agent: [rag] 0 chunks after text filter.
13:11:30 [WARNING] src.models.rag_agent: [rag] Too few filtered chunks (0) for KHC, using top FAISS results.
13:11:30 [INFO] src.models.rag_agent: [rag] Using 7 chunks for KHC.
13:12:54 [WARNING] src.models.rag_agent: [rag] Model did not return JSON. Using fallback.

[rag] Analyzing companies: 100%|██████████| 7/7 [10:00<00:00, 84.85s/it]
[rag] Analyzing companies: 100%|██████████| 7/7 [10:00<00:00, 85.73s/it]
13:12:54 [INFO] src.models.rag_agent: [rag] Predictions saved to '/content/MLOps-group-10/data/results/rag_predictions.csv'.


Running inference for lora_r32_rag — adapter: data/models/lora_adapter_r32/fold_2/lora_config_r32/final_adapter — fold: 2
STDOUT:
   PREDICTIONS SUMMARY  (approach: lora_r32_rag)
  Ticker    Company                          Score  Label  Level
  --------------------------------------------------------------------
  AAL       American Airlines                 50.0      0  medium
  TMUS      T-Mobile US                       50.0      0  medium
  ELV       Elevance Health                   50.0      0  medium
  IP        International Paper               50.0      0  medium
  FLUT      Flutter Entertainment             50.0      0  medium
  TXN       Texas Instruments                 50.0      0  medium
  FNMA      Fannie Mae                        50.0      0  medium
  Avg score: 50.0  |  High: 0  Medium: 7  Low: 0
Results saved to: /content/MLOps-group-10/data/results/lora_r32_rag_fold2_test.csv


STDERR:
 13:12:59 [INFO] run_inference_all: Starting inference: approach=lora_r32_rag, mock=False.
13:13:00 [INFO] numexpr.utils: NumExpr defaulting to 2 threads.
13:13:00 [INFO] run_inference_all: Loaded 7 companies for fold 2 split 'test'.
13:13:02 [INFO] run_inference_all: Loading base model + LoRA adapter from 'data/models/lora_adapter_r32/fold_2/lora_config_r32/final_adapter'.
13:13:08 [INFO] src.models.base_loader: HF_TOKEN found — using authenticated HuggingFace download.
13:13:08 [INFO] src.models.base_loader: Loading tokenizer for 'mistralai/Mistral-7B-Instruct-v0.2'.
13:13:09 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
13:13:09 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
13:13:09 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
13:13:09 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
13:13:09 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
13:13:09 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/tokenizer_config.json "HTTP/1.1 200 OK"
13:13:09 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
13:13:09 [INFO] httpx: HTTP Request: GET https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
13:13:09 [INFO] src.models.base_loader: 4-bit NF4 quantisation enabled.
13:13:09 [INFO] src.models.base_loader: Loading model 'mistralai/Mistral-7B-Instruct-v0.2' (device_map='auto').
13:13:09 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
13:13:09 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"
13:13:09 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
13:13:09 [INFO] httpx: HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/mistralai/Mistral-7B-Instruct-v0.2/63a8b081895390a26e140280378bc85ec8bce07a/config.json "HTTP/1.1 200 OK"

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]
Loading weights:   0%|          | 1/291 [00:00<00:00, 11037.64it/s, Materializing param=lm_head.weight]
Loading weights:   0%|          | 1/291 [00:00<00:00, 4429.04it/s, Materializing param=lm_head.weight]
Loading weights:   1%|          | 2/291 [00:01<02:31,  1.91it/s, Materializing param=lm_head.weight]
Loading weights:   1%|          | 2/291 [00:01<02:31,  1.91it/s, Materializing param=model.embed_tokens.weight]
Loading weights:   1%|          | 2/291 [00:01<02:31,  1.91it/s, Materializing param=model.embed_tokens.weight]
Loading weights:   1%|          | 3/291 [00:01<03:06,  1.54it/s, Materializing param=model.embed_tokens.weight]
Loading weights:   1%|          | 3/291 [00:01<03:06,  1.54it/s, Materializing param=model.layers.0.input_layernorm.weight]
Loading weights:   1%|          | 3/291 [00:01<03:06,  1.54it/s, Materializing param=model.layers.0.input_layernorm.weight]
Loading weights:   1%|▏         | 4/291 [00:01<03:06,  1.54it/s, Materializing param=model.layers.0.mlp.down_proj.weight]
Loading weights:   1%|▏         | 4/291 [00:01<03:06,  1.54it/s, Materializing param=model.layers.0.mlp.down_proj.weight]
Loading weights:   2%|▏         | 5/291 [00:04<04:23,  1.09it/s, Materializing param=model.layers.0.mlp.down_proj.weight]
Loading weights:   2%|▏         | 5/291 [00:04<04:23,  1.09it/s, Materializing param=model.layers.0.mlp.gate_proj.weight]
Loading weights:   2%|▏         | 5/291 [00:04<04:23,  1.09it/s, Materializing param=model.layers.0.mlp.gate_proj.weight]
Loading weights:   2%|▏         | 6/291 [00:05<04:49,  1.01s/it, Materializing param=model.layers.0.mlp.gate_proj.weight]
Loading weights:   2%|▏         | 6/291 [00:05<04:49,  1.01s/it, Materializing param=model.layers.0.mlp.up_proj.weight]
Loading weights:   2%|▏         | 6/291 [00:05<04:49,  1.01s/it, Materializing param=model.layers.0.mlp.up_proj.weight]
Loading weights:   2%|▏         | 7/291 [00:06<04:54,  1.04s/it, Materializing param=model.layers.0.mlp.up_proj.weight]
Loading weights:   2%|▏         | 7/291 [00:06<04:54,  1.04s/it, Materializing param=model.layers.0.post_attention_layernorm.weight]
Loading weights:   2%|▏         | 7/291 [00:06<04:54,  1.04s/it, Materializing param=model.layers.0.post_attention_layernorm.weight]
Loading weights:   3%|▎         | 8/291 [00:06<04:53,  1.04s/it, Materializing param=model.layers.0.self_attn.k_proj.weight]
Loading weights:   3%|▎         | 8/291 [00:06<04:53,  1.04s/it, Materializing param=model.layers.0.self_attn.k_proj.weight]
Loading weights:   3%|▎         | 9/291 [00:08<04:23,  1.07it/s, Materializing param=model.layers.0.self_attn.k_proj.weight]
Loading weights:   3%|▎         | 9/291 [00:08<04:23,  1.07it/s, Materializing param=model.layers.0.self_attn.o_proj.weight]
Loading weights:   3%|▎         | 9/291 [00:08<04:23,  1.07it/s, Materializing param=model.layers.0.self_attn.o_proj.weight]
Loading weights:   3%|▎         | 10/291 [00:11<07:02,  1.51s/it, Materializing param=model.layers.0.self_attn.o_proj.weight]
Loading weights:   3%|▎         | 10/291 [00:11<07:02,  1.51s/it, Materializing param=model.layers.0.self_attn.q_proj.weight]
Loading weights:   3%|▎         | 10/291 [00:11<07:02,  1.51s/it, Materializing param=model.layers.0.self_attn.q_proj.weight]
Loading weights:   4%|▍         | 11/291 [00:13<07:14,  1.55s/it, Materializing param=model.layers.0.self_attn.q_proj.weight]
Loading weights:   4%|▍         | 11/291 [00:13<07:14,  1.55s/it, Materializing param=model.layers.0.self_attn.v_proj.weight]
Loading weights:   4%|▍         | 11/291 [00:13<07:14,  1.55s/it, Materializing param=model.layers.0.self_attn.v_proj.weight]
Loading weights:   4%|▍         | 12/291 [00:13<06:08,  1.32s/it, Materializing param=model.layers.0.self_attn.v_proj.weight]
Loading weights:   4%|▍         | 12/291 [00:13<06:08,  1.32s/it, Materializing param=model.layers.1.input_layernorm.weight]
Loading weights:   4%|▍         | 12/291 [00:13<06:08,  1.32s/it, Materializing param=model.layers.1.input_layernorm.weight]
Loading weights:   4%|▍         | 13/291 [00:13<06:07,  1.32s/it, Materializing param=model.layers.1.mlp.down_proj.weight]
Loading weights:   4%|▍         | 13/291 [00:13<06:07,  1.32s/it, Materializing param=model.layers.1.mlp.down_proj.weight]
Loading weights:   5%|▍         | 14/291 [00:16<05:50,  1.26s/it, Materializing param=model.layers.1.mlp.down_proj.weight]
Loading weights:   5%|▍         | 14/291 [00:16<05:50,  1.26s/it, Materializing param=model.layers.1.mlp.gate_proj.weight]
Loading weights:   5%|▍         | 14/291 [00:16<05:50,  1.26s/it, Materializing param=model.layers.1.mlp.gate_proj.weight]
Loading weights:   5%|▌         | 15/291 [00:16<05:14,  1.14s/it, Materializing param=model.layers.1.mlp.gate_proj.weight]
Loading weights:   5%|▌         | 15/291 [00:16<05:14,  1.14s/it, Materializing param=model.layers.1.mlp.up_proj.weight]
Loading weights:   5%|▌         | 15/291 [00:16<05:14,  1.14s/it, Materializing param=model.layers.1.mlp.up_proj.weight]
Loading weights:   5%|▌         | 16/291 [00:19<06:19,  1.38s/it, Materializing param=model.layers.1.mlp.up_proj.weight]

---
## Section 9: Full Evaluation

Run the complete evaluation pipeline comparing all approaches:

| Approach | Description |
|----------|-------------|
| Baseline | Direct Mistral-7B prompting |
| RAG | Mistral-7B + FAISS retrieval |
| LoRA | Fine-tuned Mistral-7B adapter |
| Altman Z-Score | Classical financial model (benchmark) |

Metrics computed: Accuracy, Precision, Recall, F1, AUC-ROC.

Outputs:
- `data/results/metrics_summary.csv`
- `data/results/roc_curves.png`

In [14]:
# Run full evaluation pipeline — compares all four approaches
# This also generates Altman Z-Score predictions automatically
!python3 scripts/evaluate_folds.py

INFO:evaluate_folds:Loaded and merged 32 rows for baseline
INFO:evaluate_folds:Loaded and merged 32 rows for rag
INFO:evaluate_folds:Loaded and merged 30 rows for lora_r32
INFO:evaluate_folds:Loaded and merged 32 rows for lora_r32_rag
INFO:evaluate_folds:Loaded and merged 9 rows for altman_zscore

======================================================================
  EVALUATION OF ALL FOLDS AND COMPANIES
======================================================================
               auc_roc      f1  precision  recall  accuracy
approach
baseline        0.8494  0.0000     0.0000  0.0000    0.8125
rag             0.6923  0.4286     0.2727  1.0000    0.5000
lora_r32        0.7014  0.0000     0.0000  0.0000    0.7333
lora_r32_rag    0.5000  0.0000     0.0000  0.0000    0.8125
altman_zscore   0.7778  0.4444     0.3333  0.6667    0.4444
======================================================================

Metrics for baseline:
  auc_roc: 0.8494
  f1: 0.0
  precision: 0.0
  recall: 0.0
  accuracy: 0.8125

Metrics for rag:
  auc_roc: 0.6923
  f1: 0.4286
  precision: 0.2727
  recall: 1.0
  accuracy: 0.5

Metrics for lora_r32:
  auc_roc: 0.7014
  f1: 0.0
  precision: 0.0
  recall: 0.0
  accuracy: 0.7333

Metrics for lora_r32_rag:
  auc_roc: 0.5
  f1: 0.0
  precision: 0.0
  recall: 0.0
  accuracy: 0.8125

Metrics for altman_zscore:
  auc_roc: 0.7778
  f1: 0.4444
  precision: 0.3333
  recall: 0.6667
  accuracy: 0.4444

In [52]:
!git pull

remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0 (from 0)
Unpacking objects: 100% (4/4), 350 bytes | 350.00 KiB/s, done.
From https://github.com/pankti0/MLOps-group-10
   8c531c5..d276168  main       -> origin/main
Updating 8c531c5..d276168
Fast-forward
 scripts/evaluate_folds.py | 1 +
 1 file changed, 1 insertion(+)

In [ ]:
# Load and display the metrics summary table
import pandas as pd
from IPython.display import display
import os

metrics_path = "/content/MLOps-group-10/data/results/metrics_summary.csv"

if os.path.isfile(metrics_path):
    metrics_df = pd.read_csv(metrics_path)
    print("Evaluation Metrics Summary")
    print("=" * 60)

    # Style numeric columns
    numeric_cols = metrics_df.select_dtypes(include="number").columns.tolist()

    def highlight_best(s):
        """Highlight the best value in each numeric column green."""
        if s.name not in numeric_cols:
            return [""] * len(s)
        is_best = s == s.max()
        return ["background-color: #d4edda; font-weight: bold" if v else "" for v in is_best]

    styled = (
        metrics_df.style
        .apply(highlight_best)
        .format({col: "{:.4f}" for col in numeric_cols})
        .set_caption("Comparison of Credit Risk Detection Approaches")
        .set_table_styles([{
            "selector": "th",
            "props": [("background-color", "#343a40"), ("color", "white"), ("font-weight", "bold")]
        }])
    )
    display(styled)
else:
    print(f"Metrics summary not found at {metrics_path}. Check evaluate_folds.py output above.")

In [ ]:
# Display the ROC curves image
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os

roc_path = "/content/MLOps-group-10/data/results/roc_curves.png"

if os.path.isfile(roc_path):
    img = mpimg.imread(roc_path)
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.imshow(img)
    ax.axis("off")
    ax.set_title("ROC Curves — All Approaches", fontsize=14, fontweight="bold")
    plt.tight_layout()
    plt.show()
else:
    print(f"ROC curve image not found at {roc_path}.")

In [ ]:
# Show a per-company prediction comparison across all approaches
import pandas as pd
from IPython.display import display
import os

RESULTS_DIR = "/content/MLOps-group-10/data/results"
LABELS_PATH = "/content/MLOps-group-10/data/labels/company_labels.csv"

labels = pd.read_csv(LABELS_PATH)[["ticker", "label", "risk_category"]].rename(
    columns={"label": "true_label", "risk_category": "true_risk"}
)

comparison = labels.copy()

for approach in ["baseline", "rag", "lora_r8", "lora_r16", "lora_r32"]:
    pred_path = os.path.join(RESULTS_DIR, f"{approach}_predictions.csv")
    if os.path.isfile(pred_path):
        df = pd.read_csv(pred_path)[["ticker", "predicted_label", "predicted_score"]]
        df = df.rename(columns={
            "predicted_label": f"{approach}_pred",
            "predicted_score" : f"{approach}_score",
        })
        comparison = comparison.merge(df, on="ticker", how="left")

# Mark correct predictions
for approach in ["baseline", "rag", "lora_r8", "lora_r16", "lora_r32"]:
    col = f"{approach}_pred"
    if col in comparison.columns:
        comparison[f"{approach}_correct"] = (comparison[col] == comparison["true_label"])

print("Per-Company Prediction Comparison")
print("Green cell = correct prediction")

def highlight_correct(val):
    if val is True:
        return "background-color: #d4edda"
    elif val is False:
        return "background-color: #f8d7da"
    return ""

correct_cols = [c for c in comparison.columns if c.endswith("_correct")]
display(
    comparison.style
    .map(highlight_correct, subset=correct_cols)
    .set_caption("Prediction Comparison (green = correct, red = wrong)")
)

---
## Section 10: Download Results

Zip and download the results folder and the LoRA adapter from Colab to your local machine.

- `results.zip` — all prediction CSVs, metrics summary, ROC curves, loss curve
- `lora_adapter.zip` — the trained LoRA adapter weights (for re-use or deployment)

In [42]:
import os
import shutil
from google.colab import files

RESULTS_DIR = "/content/MLOps-group-10/data/results"
ADAPTER_DIR = "/content/MLOps-group-10/data/models/lora_adapter"

# Zip the results directory
results_zip = "/content/results"
print("Zipping data/results/ ...")
shutil.make_archive(results_zip, "zip", RESULTS_DIR)
results_zip_path = results_zip + ".zip"
size_mb = os.path.getsize(results_zip_path) / 1e6
print(f"Created {results_zip_path} ({size_mb:.1f} MB)")

# List contents
print("\nContents:")
for f in sorted(os.listdir(RESULTS_DIR)):
    fpath = os.path.join(RESULTS_DIR, f)
    sz = os.path.getsize(fpath) / 1e3
    print(f"  {f}  ({sz:.1f} KB)")

# Download
print("\nDownloading results.zip ...")
files.download(results_zip_path)

Zipping data/results/ ...
Created /content/results.zip (0.1 MB)

Contents:
  altman_zscore_predictions.csv  (1.8 KB)
  baseline_fold1_test.csv  (11.9 KB)
  baseline_fold2_test.csv  (9.5 KB)
  baseline_fold3_test.csv  (9.6 KB)
  baseline_fold4_test.csv  (9.4 KB)
  baseline_fold5_test.csv  (9.3 KB)
  baseline_predictions.csv  (9.3 KB)
  lora_predictions.csv  (14.6 KB)
  lora_r16_predictions.csv  (13.8 KB)
  lora_r32_fold1_test.csv  (9.0 KB)
  lora_r32_fold2_test.csv  (6.5 KB)
  lora_r32_fold3_test.csv  (7.6 KB)
  lora_r32_fold4_test.csv  (6.3 KB)
  lora_r32_fold5_test.csv  (7.4 KB)
  lora_r32_predictions.csv  (12.3 KB)
  lora_r8_predictions.csv  (17.2 KB)
  metrics_summary.csv  (0.3 KB)
  rag_fold1_test.csv  (7.7 KB)
  rag_fold2_test.csv  (6.4 KB)
  rag_fold3_test.csv  (5.2 KB)
  rag_fold4_test.csv  (5.1 KB)
  rag_fold5_test.csv  (5.7 KB)
  rag_predictions.csv  (5.7 KB)
  roc_curves.png  (110.4 KB)

Downloading results.zip ...

In [55]:
# Download all LoRA adapters as a single zip
import os
import shutil
from google.colab import files

ADAPTER_DIRS = {
    "lora_r16": "/content/MLOps-group-10/data/models/lora_adapter",
    "lora_r8" : "/content/MLOps-group-10/data/models/lora_adapter_r8",
    "lora_r32": "/content/MLOps-group-10/data/models/lora_adapter_r32",
}

# Bundle all available adapters into one archive
staging = "/content/lora_adapters_all"
os.makedirs(staging, exist_ok=True)

found = []
for name, src in ADAPTER_DIRS.items():
    if os.path.isdir(src):
        shutil.copytree(src, os.path.join(staging, name))
        found.append(name)
        print(f"  Included: {name}")
    else:
        print(f"  [SKIP] {name} — not found at {src}")

if found:
    zip_path = "/content/lora_adapters_all"
    print(f"\nZipping {len(found)} adapter(s)...")
    shutil.make_archive(zip_path, "zip", "/content", "lora_adapters_all")
    size_mb = os.path.getsize(zip_path + ".zip") / 1e6
    print(f"Created lora_adapters_all.zip ({size_mb:.1f} MB)")
    print("Downloading...")
    files.download(zip_path + ".zip")
else:
    print("No adapter directories found. Run Section 7 (LoRA Training) first.")

  [SKIP] lora_r16 — not found at /content/MLOps-group-10/data/models/lora_adapter
  [SKIP] lora_r8 — not found at /content/MLOps-group-10/data/models/lora_adapter_r8
  Included: lora_r32

Zipping 1 adapter(s)...
Created lora_adapters_all.zip (2496.1 MB)
Downloading...

In [ ]:
# Final summary — print W&B links and key output paths
import os

print("=" * 60)
print("  PIPELINE COMPLETE")
print("=" * 60)

output_files = {
    "Baseline predictions" : "/content/MLOps-group-10/data/results/baseline_predictions.csv",
    "RAG predictions"      : "/content/MLOps-group-10/data/results/rag_predictions.csv",
    "LoRA r=8  predictions": "/content/MLOps-group-10/data/results/lora_r8_predictions.csv",
    "LoRA r=16 predictions": "/content/MLOps-group-10/data/results/lora_r16_predictions.csv",
    "LoRA r=32 predictions": "/content/MLOps-group-10/data/results/lora_r32_predictions.csv",
    "Altman Z-Score"       : "/content/MLOps-group-10/data/results/altman_zscore_predictions.csv",
    "Metrics summary"      : "/content/MLOps-group-10/data/results/metrics_summary.csv",
    "ROC curves"           : "/content/MLOps-group-10/data/results/roc_curves.png",
    "LoRA adapter r=16"    : "/content/MLOps-group-10/data/models/lora_adapter",
    "LoRA adapter r=8"     : "/content/MLOps-group-10/data/models/lora_adapter_r8",
    "LoRA adapter r=32"    : "/content/MLOps-group-10/data/models/lora_adapter_r32",
}

print("\nOutput files:")
for name, path in output_files.items():
    exists = os.path.isfile(path) or os.path.isdir(path)
    status = "OK" if exists else "MISSING"
    print(f"  [{status:7s}] {name}")

print("\nW&B Dashboard:")
print("  https://wandb.ai → project: credit-risk-detection")
print("  Runs: lora-r8, lora-sft, lora-r32 (training) | evaluation")
print("=" * 60)